/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author ~Midori Mato~
 */
public class FormQLKhuyenmai extends javax.swing.JFrame {

    /**
     * Creates new form FormBanve
     */
    public FormQLKhuyenmai() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelHeader = new javax.swing.JLabel();
        jLabelMinimize = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jLabelQLKhuyenmai = new javax.swing.JLabel();
        jButtonBack = new javax.swing.JButton();
        jButtonNext = new javax.swing.JButton();
        jButtonThem = new javax.swing.JButton();
        jButtonSua = new javax.swing.JButton();
        jButtonXoa = new javax.swing.JButton();
        jButtonLuu = new javax.swing.JButton();
        jButtonTrangchu = new javax.swing.JButton();
        jPanelInforKhuyenmai = new javax.swing.JPanel();
        jLabelMota = new javax.swing.JLabel();
        jTextFieldMa = new javax.swing.JTextField();
        jLabelNgaybatdau = new javax.swing.JLabel();
        jLabelNgayketthuc = new javax.swing.JLabel();
        jLabelDoituong = new javax.swing.JLabel();
        jTextFieldMota = new javax.swing.JTextField();
        jDateChooserNgaybatdau = new com.toedter.calendar.JDateChooser();
        jLabelTimkiem = new javax.swing.JLabel();
        jTextFieldTimkiem = new javax.swing.JTextField();
        jComboBoxDoituong = new javax.swing.JComboBox<>();
        jLabelMa = new javax.swing.JLabel();
        jDateChooserNgayketthuc = new com.toedter.calendar.JDateChooser();
        jScrollPaneBangKhuyenmai = new javax.swing.JScrollPane();
        jTableQLKhuyenmai = new javax.swing.JTable();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(820, 478));
        setResizable(false);
        setSize(new java.awt.Dimension(820, 478));
        getContentPane().setLayout(null);

        jLabelHeader.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelHeader.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/image0.png"))); // NOI18N
        getContentPane().add(jLabelHeader);
        jLabelHeader.setBounds(0, 0, 820, 40);

        jLabelMinimize.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelMinimize);
        jLabelMinimize.setBounds(710, 0, 50, 40);

        jLabelClose.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelClose);
        jLabelClose.setBounds(770, 0, 50, 40);

        jLabelQLKhuyenmai.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabelQLKhuyenmai.setForeground(new java.awt.Color(0, 0, 204));
        jLabelQLKhuyenmai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelQLKhuyenmai.setText("Quản lý Khuyến mãi");
        getContentPane().add(jLabelQLKhuyenmai);
        jLabelQLKhuyenmai.setBounds(230, 50, 370, 50);

        jButtonBack.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonBack.setForeground(new java.awt.Color(0, 0, 204));
        jButtonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconback.png"))); // NOI18N
        jButtonBack.setText("Back");
        jButtonBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButtonBack);
        jButtonBack.setBounds(20, 413, 107, 40);

        jButtonNext.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonNext.setForeground(new java.awt.Color(0, 0, 204));
        jButtonNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconnext.png"))); // NOI18N
        jButtonNext.setText("Next");
        jButtonNext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButtonNext);
        jButtonNext.setBounds(140, 412, 105, 41);

        jButtonThem.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonThem.setForeground(new java.awt.Color(0, 0, 204));
        jButtonThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconadd.png"))); // NOI18N
        jButtonThem.setText("Thêm");
        jButtonThem.setBorder(null);
        jButtonThem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThemActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonThem);
        jButtonThem.setBounds(260, 413, 102, 40);

        jButtonSua.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonSua.setForeground(new java.awt.Color(0, 0, 204));
        jButtonSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconsua.png"))); // NOI18N
        jButtonSua.setText("Sửa");
        jButtonSua.setBorder(null);
        jButtonSua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButtonSua);
        jButtonSua.setBounds(370, 413, 88, 40);

        jButtonXoa.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonXoa.setForeground(new java.awt.Color(0, 0, 204));
        jButtonXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconxoa.png"))); // NOI18N
        jButtonXoa.setText("Xóa");
        jButtonXoa.setBorder(null);
        jButtonXoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButtonXoa);
        jButtonXoa.setBounds(470, 413, 91, 40);

        jButtonLuu.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonLuu.setForeground(new java.awt.Color(0, 0, 204));
        jButtonLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconsave.png"))); // NOI18N
        jButtonLuu.setText("Lưu");
        jButtonLuu.setBorder(null);
        jButtonLuu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButtonLuu);
        jButtonLuu.setBounds(570, 413, 88, 40);

        jButtonTrangchu.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonTrangchu.setForeground(new java.awt.Color(0, 0, 204));
        jButtonTrangchu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconmenu.png"))); // NOI18N
        jButtonTrangchu.setText("Trang chủ");
        jButtonTrangchu.setBorder(null);
        jButtonTrangchu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButtonTrangchu);
        jButtonTrangchu.setBounds(670, 413, 139, 40);

        jPanelInforKhuyenmai.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelInforKhuyenmai.setLayout(null);

        jLabelMota.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelMota.setForeground(new java.awt.Color(0, 0, 204));
        jLabelMota.setText("Mô tả:");
        jPanelInforKhuyenmai.add(jLabelMota);
        jLabelMota.setBounds(11, 119, 36, 22);

        jTextFieldMa.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldMa.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforKhuyenmai.add(jTextFieldMa);
        jTextFieldMa.setBounds(115, 90, 94, 23);

        jLabelNgaybatdau.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelNgaybatdau.setForeground(new java.awt.Color(0, 0, 204));
        jLabelNgaybatdau.setText("Ngày bắt đầu:");
        jPanelInforKhuyenmai.add(jLabelNgaybatdau);
        jLabelNgaybatdau.setBounds(11, 185, 88, 22);

        jLabelNgayketthuc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelNgayketthuc.setForeground(new java.awt.Color(0, 0, 204));
        jLabelNgayketthuc.setText("Ngày kết thúc:");
        jPanelInforKhuyenmai.add(jLabelNgayketthuc);
        jLabelNgayketthuc.setBounds(11, 213, 88, 22);

        jLabelDoituong.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelDoituong.setForeground(new java.awt.Color(0, 0, 204));
        jLabelDoituong.setText("Đối tượng:");
        jPanelInforKhuyenmai.add(jLabelDoituong);
        jLabelDoituong.setBounds(11, 241, 69, 22);

        jTextFieldMota.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldMota.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforKhuyenmai.add(jTextFieldMota);
        jTextFieldMota.setBounds(115, 119, 236, 60);

        jDateChooserNgaybatdau.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforKhuyenmai.add(jDateChooserNgaybatdau);
        jDateChooserNgaybatdau.setBounds(117, 185, 136, 22);

        jLabelTimkiem.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelTimkiem.setForeground(new java.awt.Color(0, 0, 204));
        jLabelTimkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconsearch.png"))); // NOI18N
        jLabelTimkiem.setText("Tìm kiếm:");
        jPanelInforKhuyenmai.add(jLabelTimkiem);
        jLabelTimkiem.setBounds(11, 12, 100, 31);

        jTextFieldTimkiem.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldTimkiem.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforKhuyenmai.add(jTextFieldTimkiem);
        jTextFieldTimkiem.setBounds(115, 12, 126, 31);

        jComboBoxDoituong.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jComboBoxDoituong.setForeground(new java.awt.Color(0, 0, 204));
        jComboBoxDoituong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanelInforKhuyenmai.add(jComboBoxDoituong);
        jComboBoxDoituong.setBounds(117, 241, 99, 23);

        jLabelMa.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelMa.setForeground(new java.awt.Color(0, 0, 204));
        jLabelMa.setText("Mã khuyến mãi:");
        jPanelInforKhuyenmai.add(jLabelMa);
        jLabelMa.setBounds(11, 90, 100, 22);

        jDateChooserNgayketthuc.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforKhuyenmai.add(jDateChooserNgayketthuc);
        jDateChooserNgayketthuc.setBounds(117, 213, 136, 22);

        jTableQLKhuyenmai.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTableQLKhuyenmai.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTableQLKhuyenmai.setForeground(new java.awt.Color(0, 0, 204));
        jTableQLKhuyenmai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneBangKhuyenmai.setViewportView(jTableQLKhuyenmai);

        jPanelInforKhuyenmai.add(jScrollPaneBangKhuyenmai);
        jScrollPaneBangKhuyenmai.setBounds(380, 0, 350, 290);

        getContentPane().add(jPanelInforKhuyenmai);
        jPanelInforKhuyenmai.setBounds(50, 110, 730, 290);

        jLabelBackground.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/image25.png"))); // NOI18N
        getContentPane().add(jLabelBackground);
        jLabelBackground.setBounds(0, 40, 820, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_jLabelMinimizeMouseClicked

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jButtonThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemActionPerformed

    }//GEN-LAST:event_jButtonThemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormQLKhuyenmai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormQLKhuyenmai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormQLKhuyenmai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormQLKhuyenmai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormQLKhuyenmai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonLuu;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonSua;
    private javax.swing.JButton jButtonThem;
    private javax.swing.JButton jButtonTrangchu;
    private javax.swing.JButton jButtonXoa;
    private javax.swing.JComboBox<String> jComboBoxDoituong;
    private com.toedter.calendar.JDateChooser jDateChooserNgaybatdau;
    private com.toedter.calendar.JDateChooser jDateChooserNgayketthuc;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelDoituong;
    private javax.swing.JLabel jLabelHeader;
    private javax.swing.JLabel jLabelMa;
    private javax.swing.JLabel jLabelMinimize;
    private javax.swing.JLabel jLabelMota;
    private javax.swing.JLabel jLabelNgaybatdau;
    private javax.swing.JLabel jLabelNgayketthuc;
    private javax.swing.JLabel jLabelQLKhuyenmai;
    private javax.swing.JLabel jLabelTimkiem;
    private javax.swing.JPanel jPanelInforKhuyenmai;
    private javax.swing.JScrollPane jScrollPaneBangKhuyenmai;
    private javax.swing.JTable jTableQLKhuyenmai;
    private javax.swing.JTextField jTextFieldMa;
    private javax.swing.JTextField jTextFieldMota;
    private javax.swing.JTextField jTextFieldTimkiem;
    // End of variables declaration//GEN-END:variables
}
