/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author ~Midori Mato~
 */
public class FormQLKhachhang extends javax.swing.JFrame {

    /**
     * Creates new form FormQLKhachhang
     */
    public FormQLKhachhang() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMinimize = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jLabelHeader = new javax.swing.JLabel();
        jTabbedPaneQLKH = new javax.swing.JTabbedPane();
        jPanelQLkhachhang = new javax.swing.JPanel();
        jLabeQLKH = new javax.swing.JLabel();
        jButtonBack1 = new javax.swing.JButton();
        jButtonNext1 = new javax.swing.JButton();
        jButtonXoa1 = new javax.swing.JButton();
        jButtonLuu1 = new javax.swing.JButton();
        jButtonSua1 = new javax.swing.JButton();
        jButtonThem1 = new javax.swing.JButton();
        jButtonTrangchu1 = new javax.swing.JButton();
        jPanelInforKH = new javax.swing.JPanel();
        jLabelTen1 = new javax.swing.JLabel();
        jTextFieldMa1 = new javax.swing.JTextField();
        jTextFieldTen1 = new javax.swing.JTextField();
        jLabelNgaysinh = new javax.swing.JLabel();
        jLabelGioitinh = new javax.swing.JLabel();
        jRadioButtonNam = new javax.swing.JRadioButton();
        jRadioButtonNu = new javax.swing.JRadioButton();
        jLabelDiachi = new javax.swing.JLabel();
        jTextFieldDiachi = new javax.swing.JTextField();
        jLabelSodienthoai = new javax.swing.JLabel();
        jTextFieldSodienthoai = new javax.swing.JTextField();
        jLabelSoCMND = new javax.swing.JLabel();
        jTextFieldSoCMND = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelDiem = new javax.swing.JLabel();
        jLabelLoaithe = new javax.swing.JLabel();
        jTextFieldDiem = new javax.swing.JTextField();
        jDateChooserNgaysinh = new com.toedter.calendar.JDateChooser();
        jLabelTimkiem1 = new javax.swing.JLabel();
        jTextFieldTimkiem1 = new javax.swing.JTextField();
        jComboBoxLoaithe1 = new javax.swing.JComboBox<>();
        jLabelMa1 = new javax.swing.JLabel();
        jLabelNgaydangky = new javax.swing.JLabel();
        jDateChooserNgaydangky = new com.toedter.calendar.JDateChooser();
        jScrollPaneBangKH = new javax.swing.JScrollPane();
        jTableQLKH = new javax.swing.JTable();
        jLabelBackground1 = new javax.swing.JLabel();
        jPanelQLLoaithe = new javax.swing.JPanel();
        jLabelQLLoaithe = new javax.swing.JLabel();
        jPanelInforLoaithe = new javax.swing.JPanel();
        jLabelTen2 = new javax.swing.JLabel();
        jTextFieldMa2 = new javax.swing.JTextField();
        jLabelDiemtoida = new javax.swing.JLabel();
        jLabelHeso = new javax.swing.JLabel();
        jTextFieldHeso = new javax.swing.JTextField();
        jLabelTimkiem2 = new javax.swing.JLabel();
        jTextFieldTimkiem2 = new javax.swing.JTextField();
        jLabelMa2 = new javax.swing.JLabel();
        jTextFieldDiemtoida = new javax.swing.JTextField();
        jComboBoxLoaithe2 = new javax.swing.JComboBox<>();
        jScrollPaneBangLoaithe = new javax.swing.JScrollPane();
        jTableQLThe = new javax.swing.JTable();
        jButtonBack3 = new javax.swing.JButton();
        jButtonNext2 = new javax.swing.JButton();
        jButtonThem3 = new javax.swing.JButton();
        jButtonSua2 = new javax.swing.JButton();
        jButtonXoa3 = new javax.swing.JButton();
        jButtonLuu3 = new javax.swing.JButton();
        jButtonTrangchu3 = new javax.swing.JButton();
        jLabelbackground2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(820, 478));
        setResizable(false);
        setSize(new java.awt.Dimension(820, 478));
        getContentPane().setLayout(null);

        jLabelMinimize.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelMinimize);
        jLabelMinimize.setBounds(710, 0, 50, 40);

        jLabelClose.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelClose);
        jLabelClose.setBounds(770, 0, 50, 40);

        jLabelHeader.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelHeader.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/image0.png"))); // NOI18N
        getContentPane().add(jLabelHeader);
        jLabelHeader.setBounds(0, 0, 820, 40);

        jTabbedPaneQLKH.setForeground(new java.awt.Color(0, 0, 204));

        jPanelQLkhachhang.setLayout(null);

        jLabeQLKH.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabeQLKH.setForeground(new java.awt.Color(255, 0, 0));
        jLabeQLKH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeQLKH.setText("Quản lý Khách hàng");
        jPanelQLkhachhang.add(jLabeQLKH);
        jLabeQLKH.setBounds(260, 10, 340, 50);

        jButtonBack1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonBack1.setForeground(new java.awt.Color(0, 0, 204));
        jButtonBack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconback.png"))); // NOI18N
        jButtonBack1.setText("Back");
        jButtonBack1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelQLkhachhang.add(jButtonBack1);
        jButtonBack1.setBounds(10, 353, 107, 40);

        jButtonNext1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonNext1.setForeground(new java.awt.Color(0, 0, 204));
        jButtonNext1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconnext.png"))); // NOI18N
        jButtonNext1.setText("Next");
        jButtonNext1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelQLkhachhang.add(jButtonNext1);
        jButtonNext1.setBounds(127, 353, 105, 40);

        jButtonXoa1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonXoa1.setForeground(new java.awt.Color(0, 0, 204));
        jButtonXoa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconxoa.png"))); // NOI18N
        jButtonXoa1.setText("Xóa");
        jButtonXoa1.setBorder(null);
        jButtonXoa1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelQLkhachhang.add(jButtonXoa1);
        jButtonXoa1.setBounds(458, 353, 91, 40);

        jButtonLuu1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonLuu1.setForeground(new java.awt.Color(0, 0, 204));
        jButtonLuu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconsave.png"))); // NOI18N
        jButtonLuu1.setText("Lưu");
        jButtonLuu1.setBorder(null);
        jButtonLuu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelQLkhachhang.add(jButtonLuu1);
        jButtonLuu1.setBounds(559, 353, 88, 40);

        jButtonSua1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonSua1.setForeground(new java.awt.Color(0, 0, 204));
        jButtonSua1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconsua.png"))); // NOI18N
        jButtonSua1.setText("Sửa");
        jButtonSua1.setBorder(null);
        jButtonSua1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelQLkhachhang.add(jButtonSua1);
        jButtonSua1.setBounds(354, 353, 88, 40);

        jButtonThem1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonThem1.setForeground(new java.awt.Color(0, 0, 204));
        jButtonThem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconadd.png"))); // NOI18N
        jButtonThem1.setText("Thêm");
        jButtonThem1.setBorder(null);
        jButtonThem1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonThem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThem1ActionPerformed(evt);
            }
        });
        jPanelQLkhachhang.add(jButtonThem1);
        jButtonThem1.setBounds(242, 353, 102, 40);

        jButtonTrangchu1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonTrangchu1.setForeground(new java.awt.Color(0, 0, 204));
        jButtonTrangchu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconmenu.png"))); // NOI18N
        jButtonTrangchu1.setText("Trang chủ");
        jButtonTrangchu1.setBorder(null);
        jButtonTrangchu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelQLkhachhang.add(jButtonTrangchu1);
        jButtonTrangchu1.setBounds(657, 353, 139, 40);

        jPanelInforKH.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelInforKH.setLayout(null);

        jLabelTen1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelTen1.setForeground(new java.awt.Color(0, 0, 204));
        jLabelTen1.setText("Tên khách hàng:");
        jPanelInforKH.add(jLabelTen1);
        jLabelTen1.setBounds(11, 78, 100, 22);

        jTextFieldMa1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldMa1.setForeground(new java.awt.Color(0, 0, 204));
        jTextFieldMa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMa1ActionPerformed(evt);
            }
        });
        jPanelInforKH.add(jTextFieldMa1);
        jTextFieldMa1.setBounds(115, 49, 87, 23);

        jTextFieldTen1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldTen1.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforKH.add(jTextFieldTen1);
        jTextFieldTen1.setBounds(115, 78, 197, 23);

        jLabelNgaysinh.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelNgaysinh.setForeground(new java.awt.Color(0, 0, 204));
        jLabelNgaysinh.setText("Ngày sinh:");
        jPanelInforKH.add(jLabelNgaysinh);
        jLabelNgaysinh.setBounds(11, 107, 68, 22);

        jLabelGioitinh.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelGioitinh.setForeground(new java.awt.Color(0, 0, 204));
        jLabelGioitinh.setText("Giới tính:");
        jPanelInforKH.add(jLabelGioitinh);
        jLabelGioitinh.setBounds(11, 135, 68, 22);

        jRadioButtonNam.setForeground(new java.awt.Color(0, 0, 204));
        jRadioButtonNam.setText("Nam");
        jPanelInforKH.add(jRadioButtonNam);
        jRadioButtonNam.setBounds(79, 137, 47, 23);

        jRadioButtonNu.setForeground(new java.awt.Color(0, 0, 204));
        jRadioButtonNu.setText("Nữ");
        jPanelInforKH.add(jRadioButtonNu);
        jRadioButtonNu.setBounds(136, 137, 39, 23);

        jLabelDiachi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelDiachi.setForeground(new java.awt.Color(0, 0, 204));
        jLabelDiachi.setText("Địa chỉ:");
        jPanelInforKH.add(jLabelDiachi);
        jLabelDiachi.setBounds(11, 166, 54, 22);

        jTextFieldDiachi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldDiachi.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforKH.add(jTextFieldDiachi);
        jTextFieldDiachi.setBounds(69, 166, 354, 23);

        jLabelSodienthoai.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelSodienthoai.setForeground(new java.awt.Color(0, 0, 204));
        jLabelSodienthoai.setText("Số điện thoại:");
        jPanelInforKH.add(jLabelSodienthoai);
        jLabelSodienthoai.setBounds(11, 195, 85, 22);

        jTextFieldSodienthoai.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldSodienthoai.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforKH.add(jTextFieldSodienthoai);
        jTextFieldSodienthoai.setBounds(100, 195, 123, 23);

        jLabelSoCMND.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelSoCMND.setForeground(new java.awt.Color(0, 0, 204));
        jLabelSoCMND.setText("Số CMND:");
        jPanelInforKH.add(jLabelSoCMND);
        jLabelSoCMND.setBounds(227, 195, 63, 22);

        jTextFieldSoCMND.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldSoCMND.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforKH.add(jTextFieldSoCMND);
        jTextFieldSoCMND.setBounds(300, 195, 117, 23);

        jLabelEmail.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelEmail.setForeground(new java.awt.Color(0, 0, 204));
        jLabelEmail.setText("Email:");
        jPanelInforKH.add(jLabelEmail);
        jLabelEmail.setBounds(11, 224, 44, 22);

        jTextFieldEmail.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldEmail.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforKH.add(jTextFieldEmail);
        jTextFieldEmail.setBounds(59, 224, 164, 23);

        jLabelDiem.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelDiem.setForeground(new java.awt.Color(0, 0, 204));
        jLabelDiem.setText("Điểm:");
        jPanelInforKH.add(jLabelDiem);
        jLabelDiem.setBounds(451, 224, 42, 22);

        jLabelLoaithe.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelLoaithe.setForeground(new java.awt.Color(0, 0, 204));
        jLabelLoaithe.setText("Loại thẻ:");
        jPanelInforKH.add(jLabelLoaithe);
        jLabelLoaithe.setBounds(259, 224, 57, 22);

        jTextFieldDiem.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldDiem.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforKH.add(jTextFieldDiem);
        jTextFieldDiem.setBounds(497, 224, 88, 23);

        jDateChooserNgaysinh.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforKH.add(jDateChooserNgaysinh);
        jDateChooserNgaysinh.setBounds(89, 107, 136, 22);

        jLabelTimkiem1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelTimkiem1.setForeground(new java.awt.Color(0, 0, 204));
        jLabelTimkiem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconsearch.png"))); // NOI18N
        jLabelTimkiem1.setText("Tìm kiếm:");
        jPanelInforKH.add(jLabelTimkiem1);
        jLabelTimkiem1.setBounds(11, 12, 100, 31);

        jTextFieldTimkiem1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldTimkiem1.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforKH.add(jTextFieldTimkiem1);
        jTextFieldTimkiem1.setBounds(115, 12, 126, 31);

        jComboBoxLoaithe1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jComboBoxLoaithe1.setForeground(new java.awt.Color(0, 0, 204));
        jComboBoxLoaithe1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanelInforKH.add(jComboBoxLoaithe1);
        jComboBoxLoaithe1.setBounds(320, 224, 99, 23);

        jLabelMa1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelMa1.setForeground(new java.awt.Color(0, 0, 204));
        jLabelMa1.setText("Mã khách hàng:");
        jPanelInforKH.add(jLabelMa1);
        jLabelMa1.setBounds(11, 49, 100, 22);

        jLabelNgaydangky.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelNgaydangky.setForeground(new java.awt.Color(0, 0, 204));
        jLabelNgaydangky.setText("Ngày đăng ký:");
        jPanelInforKH.add(jLabelNgaydangky);
        jLabelNgaydangky.setBounds(193, 136, 90, 22);

        jDateChooserNgaydangky.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforKH.add(jDateChooserNgaydangky);
        jDateChooserNgaydangky.setBounds(287, 136, 136, 22);

        jTableQLKH.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTableQLKH.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTableQLKH.setForeground(new java.awt.Color(0, 0, 204));
        jTableQLKH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneBangKH.setViewportView(jTableQLKH);

        jPanelInforKH.add(jScrollPaneBangKH);
        jScrollPaneBangKH.setBounds(430, 0, 360, 200);

        jPanelQLkhachhang.add(jPanelInforKH);
        jPanelInforKH.setBounds(10, 70, 790, 260);

        jLabelBackground1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBackground1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/image9.png"))); // NOI18N
        jLabelBackground1.setText("jLabel1");
        jPanelQLkhachhang.add(jLabelBackground1);
        jLabelBackground1.setBounds(0, 0, 810, 400);

        jTabbedPaneQLKH.addTab("QL Khách hàng", jPanelQLkhachhang);

        jPanelQLLoaithe.setLayout(null);

        jLabelQLLoaithe.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabelQLLoaithe.setForeground(new java.awt.Color(255, 0, 0));
        jLabelQLLoaithe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelQLLoaithe.setText("Quản lý loại thẻ thành viên");
        jPanelQLLoaithe.add(jLabelQLLoaithe);
        jLabelQLLoaithe.setBounds(210, 10, 420, 40);

        jPanelInforLoaithe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelInforLoaithe.setLayout(null);

        jLabelTen2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelTen2.setForeground(new java.awt.Color(0, 0, 204));
        jLabelTen2.setText("Tên loại thẻ:");
        jPanelInforLoaithe.add(jLabelTen2);
        jLabelTen2.setBounds(11, 97, 86, 22);

        jTextFieldMa2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldMa2.setForeground(new java.awt.Color(0, 0, 204));
        jTextFieldMa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMa2ActionPerformed(evt);
            }
        });
        jPanelInforLoaithe.add(jTextFieldMa2);
        jTextFieldMa2.setBounds(107, 68, 107, 23);

        jLabelDiemtoida.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelDiemtoida.setForeground(new java.awt.Color(0, 0, 204));
        jLabelDiemtoida.setText("Điểm tối đa:");
        jPanelInforLoaithe.add(jLabelDiemtoida);
        jLabelDiemtoida.setBounds(11, 126, 68, 22);

        jLabelHeso.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelHeso.setForeground(new java.awt.Color(0, 0, 204));
        jLabelHeso.setText("Hệ số tích lũy:");
        jPanelInforLoaithe.add(jLabelHeso);
        jLabelHeso.setBounds(11, 155, 85, 22);

        jTextFieldHeso.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldHeso.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforLoaithe.add(jTextFieldHeso);
        jTextFieldHeso.setBounds(106, 155, 123, 23);

        jLabelTimkiem2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelTimkiem2.setForeground(new java.awt.Color(0, 0, 204));
        jLabelTimkiem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconsearch.png"))); // NOI18N
        jLabelTimkiem2.setText("Tìm kiếm:");
        jPanelInforLoaithe.add(jLabelTimkiem2);
        jLabelTimkiem2.setBounds(11, 12, 100, 31);

        jTextFieldTimkiem2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldTimkiem2.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforLoaithe.add(jTextFieldTimkiem2);
        jTextFieldTimkiem2.setBounds(115, 12, 126, 31);

        jLabelMa2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelMa2.setForeground(new java.awt.Color(0, 0, 204));
        jLabelMa2.setText("Mã loại thẻ:");
        jPanelInforLoaithe.add(jLabelMa2);
        jLabelMa2.setBounds(11, 68, 86, 22);

        jTextFieldDiemtoida.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldDiemtoida.setForeground(new java.awt.Color(0, 0, 204));
        jTextFieldDiemtoida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDiemtoidaActionPerformed(evt);
            }
        });
        jPanelInforLoaithe.add(jTextFieldDiemtoida);
        jTextFieldDiemtoida.setBounds(106, 126, 87, 23);

        jComboBoxLoaithe2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jComboBoxLoaithe2.setForeground(new java.awt.Color(0, 0, 204));
        jComboBoxLoaithe2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanelInforLoaithe.add(jComboBoxLoaithe2);
        jComboBoxLoaithe2.setBounds(107, 97, 99, 23);

        jTableQLThe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTableQLThe.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTableQLThe.setForeground(new java.awt.Color(0, 0, 204));
        jTableQLThe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneBangLoaithe.setViewportView(jTableQLThe);

        jPanelInforLoaithe.add(jScrollPaneBangLoaithe);
        jScrollPaneBangLoaithe.setBounds(280, 0, 320, 270);

        jPanelQLLoaithe.add(jPanelInforLoaithe);
        jPanelInforLoaithe.setBounds(110, 70, 600, 270);

        jButtonBack3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonBack3.setForeground(new java.awt.Color(0, 0, 204));
        jButtonBack3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconback.png"))); // NOI18N
        jButtonBack3.setText("Back");
        jButtonBack3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelQLLoaithe.add(jButtonBack3);
        jButtonBack3.setBounds(10, 353, 107, 40);

        jButtonNext2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonNext2.setForeground(new java.awt.Color(0, 0, 204));
        jButtonNext2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconnext.png"))); // NOI18N
        jButtonNext2.setText("Next");
        jButtonNext2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelQLLoaithe.add(jButtonNext2);
        jButtonNext2.setBounds(127, 353, 105, 40);

        jButtonThem3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonThem3.setForeground(new java.awt.Color(0, 0, 204));
        jButtonThem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconadd.png"))); // NOI18N
        jButtonThem3.setText("Thêm");
        jButtonThem3.setBorder(null);
        jButtonThem3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonThem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThem3ActionPerformed(evt);
            }
        });
        jPanelQLLoaithe.add(jButtonThem3);
        jButtonThem3.setBounds(242, 353, 102, 40);

        jButtonSua2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonSua2.setForeground(new java.awt.Color(0, 0, 204));
        jButtonSua2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconsua.png"))); // NOI18N
        jButtonSua2.setText("Sửa");
        jButtonSua2.setBorder(null);
        jButtonSua2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelQLLoaithe.add(jButtonSua2);
        jButtonSua2.setBounds(354, 353, 88, 40);

        jButtonXoa3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonXoa3.setForeground(new java.awt.Color(0, 0, 204));
        jButtonXoa3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconxoa.png"))); // NOI18N
        jButtonXoa3.setText("Xóa");
        jButtonXoa3.setBorder(null);
        jButtonXoa3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelQLLoaithe.add(jButtonXoa3);
        jButtonXoa3.setBounds(458, 353, 91, 40);

        jButtonLuu3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonLuu3.setForeground(new java.awt.Color(0, 0, 204));
        jButtonLuu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconsave.png"))); // NOI18N
        jButtonLuu3.setText("Lưu");
        jButtonLuu3.setBorder(null);
        jButtonLuu3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelQLLoaithe.add(jButtonLuu3);
        jButtonLuu3.setBounds(559, 353, 88, 40);

        jButtonTrangchu3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonTrangchu3.setForeground(new java.awt.Color(0, 0, 204));
        jButtonTrangchu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconmenu.png"))); // NOI18N
        jButtonTrangchu3.setText("Trang chủ");
        jButtonTrangchu3.setBorder(null);
        jButtonTrangchu3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelQLLoaithe.add(jButtonTrangchu3);
        jButtonTrangchu3.setBounds(657, 353, 139, 40);

        jLabelbackground2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelbackground2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/image11.png"))); // NOI18N
        jPanelQLLoaithe.add(jLabelbackground2);
        jLabelbackground2.setBounds(0, 0, 820, 410);

        jTabbedPaneQLKH.addTab("QL Loại thẻ thành viên", jPanelQLLoaithe);

        getContentPane().add(jTabbedPaneQLKH);
        jTabbedPaneQLKH.setBounds(0, 46, 820, 432);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_jLabelMinimizeMouseClicked

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jButtonThem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThem1ActionPerformed
        
    }//GEN-LAST:event_jButtonThem1ActionPerformed

    private void jTextFieldMa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMa1ActionPerformed

    private void jTextFieldMa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMa2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMa2ActionPerformed

    private void jTextFieldDiemtoidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDiemtoidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDiemtoidaActionPerformed

    private void jButtonThem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonThem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormQLKhachhang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormQLKhachhang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormQLKhachhang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormQLKhachhang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormQLKhachhang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack1;
    private javax.swing.JButton jButtonBack3;
    private javax.swing.JButton jButtonLuu1;
    private javax.swing.JButton jButtonLuu3;
    private javax.swing.JButton jButtonNext1;
    private javax.swing.JButton jButtonNext2;
    private javax.swing.JButton jButtonSua1;
    private javax.swing.JButton jButtonSua2;
    private javax.swing.JButton jButtonThem1;
    private javax.swing.JButton jButtonThem3;
    private javax.swing.JButton jButtonTrangchu1;
    private javax.swing.JButton jButtonTrangchu3;
    private javax.swing.JButton jButtonXoa1;
    private javax.swing.JButton jButtonXoa3;
    private javax.swing.JComboBox<String> jComboBoxLoaithe1;
    private javax.swing.JComboBox<String> jComboBoxLoaithe2;
    private com.toedter.calendar.JDateChooser jDateChooserNgaydangky;
    private com.toedter.calendar.JDateChooser jDateChooserNgaysinh;
    private javax.swing.JLabel jLabeQLKH;
    private javax.swing.JLabel jLabelBackground1;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelDiachi;
    private javax.swing.JLabel jLabelDiem;
    private javax.swing.JLabel jLabelDiemtoida;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelGioitinh;
    private javax.swing.JLabel jLabelHeader;
    private javax.swing.JLabel jLabelHeso;
    private javax.swing.JLabel jLabelLoaithe;
    private javax.swing.JLabel jLabelMa1;
    private javax.swing.JLabel jLabelMa2;
    private javax.swing.JLabel jLabelMinimize;
    private javax.swing.JLabel jLabelNgaydangky;
    private javax.swing.JLabel jLabelNgaysinh;
    private javax.swing.JLabel jLabelQLLoaithe;
    private javax.swing.JLabel jLabelSoCMND;
    private javax.swing.JLabel jLabelSodienthoai;
    private javax.swing.JLabel jLabelTen1;
    private javax.swing.JLabel jLabelTen2;
    private javax.swing.JLabel jLabelTimkiem1;
    private javax.swing.JLabel jLabelTimkiem2;
    private javax.swing.JLabel jLabelbackground2;
    private javax.swing.JPanel jPanelInforKH;
    private javax.swing.JPanel jPanelInforLoaithe;
    private javax.swing.JPanel jPanelQLLoaithe;
    private javax.swing.JPanel jPanelQLkhachhang;
    private javax.swing.JRadioButton jRadioButtonNam;
    private javax.swing.JRadioButton jRadioButtonNu;
    private javax.swing.JScrollPane jScrollPaneBangKH;
    private javax.swing.JScrollPane jScrollPaneBangLoaithe;
    private javax.swing.JTabbedPane jTabbedPaneQLKH;
    private javax.swing.JTable jTableQLKH;
    private javax.swing.JTable jTableQLThe;
    private javax.swing.JTextField jTextFieldDiachi;
    private javax.swing.JTextField jTextFieldDiem;
    private javax.swing.JTextField jTextFieldDiemtoida;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldHeso;
    private javax.swing.JTextField jTextFieldMa1;
    private javax.swing.JTextField jTextFieldMa2;
    private javax.swing.JTextField jTextFieldSoCMND;
    private javax.swing.JTextField jTextFieldSodienthoai;
    private javax.swing.JTextField jTextFieldTen1;
    private javax.swing.JTextField jTextFieldTimkiem1;
    private javax.swing.JTextField jTextFieldTimkiem2;
    // End of variables declaration//GEN-END:variables
}
