/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author ~Midori Mato~
 */
public class FormQLGiave extends javax.swing.JFrame {

    /**
     * Creates new form FormBanve
     */
    public FormQLGiave() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelHeader = new javax.swing.JLabel();
        jLabelMinimize = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelQLGialichchieu = new javax.swing.JPanel();
        jLabelQLGialichchieu = new javax.swing.JLabel();
        jButtonBack1 = new javax.swing.JButton();
        jButtonNext1 = new javax.swing.JButton();
        jButtonThem1 = new javax.swing.JButton();
        jButtonSua1 = new javax.swing.JButton();
        jButtonXoa1 = new javax.swing.JButton();
        jButtonLuu1 = new javax.swing.JButton();
        jButtonTrangchu1 = new javax.swing.JButton();
        jPanelInforGialichchieu = new javax.swing.JPanel();
        jLabelTenloaithe = new javax.swing.JLabel();
        jTextFieldMa1 = new javax.swing.JTextField();
        jLabelThu = new javax.swing.JLabel();
        jLabelTgbatdau = new javax.swing.JLabel();
        jTextFieldTgbatdau = new javax.swing.JTextField();
        jLabelTgketthuc = new javax.swing.JLabel();
        jTextFieldThu = new javax.swing.JTextField();
        jLabelTrigia = new javax.swing.JLabel();
        jTextFieldTgketthuc = new javax.swing.JTextField();
        jTextFieldTrigia = new javax.swing.JTextField();
        jLabelTimkiem1 = new javax.swing.JLabel();
        jTextFieldTimkiem1 = new javax.swing.JTextField();
        jLabelMagia = new javax.swing.JLabel();
        jComboBoxTenloaithe = new javax.swing.JComboBox<>();
        jScrollPaneBangGialichchieu = new javax.swing.JScrollPane();
        jTableQLGialichchieu = new javax.swing.JTable();
        jLabelBackground1 = new javax.swing.JLabel();
        jPanelQLVe = new javax.swing.JPanel();
        jLabelQLVe = new javax.swing.JLabel();
        jButtonBack2 = new javax.swing.JButton();
        jButtonNext2 = new javax.swing.JButton();
        jButtonThem2 = new javax.swing.JButton();
        jButtonSua2 = new javax.swing.JButton();
        jButtonXoa2 = new javax.swing.JButton();
        jButtonLuu2 = new javax.swing.JButton();
        jButtonTrangchu2 = new javax.swing.JButton();
        jPanelInforVe = new javax.swing.JPanel();
        jLabelMalichchieu = new javax.swing.JLabel();
        jTextFieldMave = new javax.swing.JTextField();
        jTextFieldMalichchieu = new javax.swing.JTextField();
        jLabelMakhuyenmai = new javax.swing.JLabel();
        jLabelMaghe = new javax.swing.JLabel();
        jLabelManhanvien = new javax.swing.JLabel();
        jTextFieldMakhuyenmai = new javax.swing.JTextField();
        jLabelMaKH = new javax.swing.JLabel();
        jTextFieldManhanvien = new javax.swing.JTextField();
        jLabelTongtien = new javax.swing.JLabel();
        jTextFieldThoidiemxuatve = new javax.swing.JTextField();
        jLabelNgãyuatve = new javax.swing.JLabel();
        jTextFieldMaghe = new javax.swing.JTextField();
        jLabelDiemtichluy = new javax.swing.JLabel();
        jLabelThoidiemxuatve = new javax.swing.JLabel();
        jDateChooserNgayxuatve = new com.toedter.calendar.JDateChooser();
        jLabelTimkiem2 = new javax.swing.JLabel();
        jTextFieldTimkiem2 = new javax.swing.JTextField();
        jLabelMave = new javax.swing.JLabel();
        jTextFieldTongtien = new javax.swing.JTextField();
        jTextFieldDiemtichluy = new javax.swing.JTextField();
        jTextFieldMaKH = new javax.swing.JTextField();
        jScrollPaneBangVe = new javax.swing.JScrollPane();
        jTableQLVe = new javax.swing.JTable();
        jLabelBackground2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(820, 478));
        setSize(new java.awt.Dimension(820, 478));
        getContentPane().setLayout(null);

        jLabelHeader.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelHeader.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/image0.png"))); // NOI18N
        getContentPane().add(jLabelHeader);
        jLabelHeader.setBounds(0, 0, 820, 40);

        jLabelMinimize.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelMinimize);
        jLabelMinimize.setBounds(710, 0, 50, 40);

        jLabelClose.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelClose);
        jLabelClose.setBounds(770, 0, 50, 40);

        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 255));

        jPanelQLGialichchieu.setLayout(null);

        jLabelQLGialichchieu.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabelQLGialichchieu.setForeground(new java.awt.Color(0, 0, 255));
        jLabelQLGialichchieu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelQLGialichchieu.setText("Quản lý Giá lịch chiếu");
        jPanelQLGialichchieu.add(jLabelQLGialichchieu);
        jLabelQLGialichchieu.setBounds(230, 10, 380, 50);

        jButtonBack1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonBack1.setForeground(new java.awt.Color(0, 0, 204));
        jButtonBack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconback.png"))); // NOI18N
        jButtonBack1.setText("Back");
        jButtonBack1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelQLGialichchieu.add(jButtonBack1);
        jButtonBack1.setBounds(10, 353, 107, 40);

        jButtonNext1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonNext1.setForeground(new java.awt.Color(0, 0, 204));
        jButtonNext1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconnext.png"))); // NOI18N
        jButtonNext1.setText("Next");
        jButtonNext1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelQLGialichchieu.add(jButtonNext1);
        jButtonNext1.setBounds(127, 353, 105, 40);

        jButtonThem1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonThem1.setForeground(new java.awt.Color(0, 0, 204));
        jButtonThem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconadd.png"))); // NOI18N
        jButtonThem1.setText("Thêm");
        jButtonThem1.setBorder(null);
        jButtonThem1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonThem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThem1ActionPerformed(evt);
            }
        });
        jPanelQLGialichchieu.add(jButtonThem1);
        jButtonThem1.setBounds(242, 353, 102, 40);

        jButtonSua1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonSua1.setForeground(new java.awt.Color(0, 0, 204));
        jButtonSua1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconsua.png"))); // NOI18N
        jButtonSua1.setText("Sửa");
        jButtonSua1.setBorder(null);
        jButtonSua1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelQLGialichchieu.add(jButtonSua1);
        jButtonSua1.setBounds(354, 353, 88, 40);

        jButtonXoa1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonXoa1.setForeground(new java.awt.Color(0, 0, 204));
        jButtonXoa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconxoa.png"))); // NOI18N
        jButtonXoa1.setText("Xóa");
        jButtonXoa1.setBorder(null);
        jButtonXoa1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelQLGialichchieu.add(jButtonXoa1);
        jButtonXoa1.setBounds(458, 353, 91, 40);

        jButtonLuu1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonLuu1.setForeground(new java.awt.Color(0, 0, 204));
        jButtonLuu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconsave.png"))); // NOI18N
        jButtonLuu1.setText("Lưu");
        jButtonLuu1.setBorder(null);
        jButtonLuu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelQLGialichchieu.add(jButtonLuu1);
        jButtonLuu1.setBounds(559, 353, 88, 40);

        jButtonTrangchu1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonTrangchu1.setForeground(new java.awt.Color(0, 0, 204));
        jButtonTrangchu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconmenu.png"))); // NOI18N
        jButtonTrangchu1.setText("Trang chủ");
        jButtonTrangchu1.setBorder(null);
        jButtonTrangchu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelQLGialichchieu.add(jButtonTrangchu1);
        jButtonTrangchu1.setBounds(657, 353, 139, 40);

        jPanelInforGialichchieu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelInforGialichchieu.setLayout(null);

        jLabelTenloaithe.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelTenloaithe.setForeground(new java.awt.Color(0, 0, 204));
        jLabelTenloaithe.setText("Tên loại thẻ:");
        jPanelInforGialichchieu.add(jLabelTenloaithe);
        jLabelTenloaithe.setBounds(11, 83, 100, 22);

        jTextFieldMa1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldMa1.setForeground(new java.awt.Color(0, 0, 204));
        jTextFieldMa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMa1ActionPerformed(evt);
            }
        });
        jPanelInforGialichchieu.add(jTextFieldMa1);
        jTextFieldMa1.setBounds(125, 54, 128, 23);

        jLabelThu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelThu.setForeground(new java.awt.Color(0, 0, 204));
        jLabelThu.setText("Thứ:");
        jPanelInforGialichchieu.add(jLabelThu);
        jLabelThu.setBounds(11, 109, 40, 22);

        jLabelTgbatdau.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelTgbatdau.setForeground(new java.awt.Color(0, 0, 204));
        jLabelTgbatdau.setText("Thời gian bắt đầu:");
        jPanelInforGialichchieu.add(jLabelTgbatdau);
        jLabelTgbatdau.setBounds(11, 138, 115, 22);

        jTextFieldTgbatdau.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldTgbatdau.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforGialichchieu.add(jTextFieldTgbatdau);
        jTextFieldTgbatdau.setBounds(125, 138, 127, 23);

        jLabelTgketthuc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelTgketthuc.setForeground(new java.awt.Color(0, 0, 204));
        jLabelTgketthuc.setText("Thời gian kết thúc:");
        jPanelInforGialichchieu.add(jLabelTgketthuc);
        jLabelTgketthuc.setBounds(11, 167, 115, 22);

        jTextFieldThu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldThu.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforGialichchieu.add(jTextFieldThu);
        jTextFieldThu.setBounds(125, 109, 127, 23);

        jLabelTrigia.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelTrigia.setForeground(new java.awt.Color(0, 0, 204));
        jLabelTrigia.setText("Trị giá:");
        jPanelInforGialichchieu.add(jLabelTrigia);
        jLabelTrigia.setBounds(11, 196, 44, 22);

        jTextFieldTgketthuc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldTgketthuc.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforGialichchieu.add(jTextFieldTgketthuc);
        jTextFieldTgketthuc.setBounds(125, 167, 127, 23);

        jTextFieldTrigia.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldTrigia.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforGialichchieu.add(jTextFieldTrigia);
        jTextFieldTrigia.setBounds(125, 196, 94, 23);

        jLabelTimkiem1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelTimkiem1.setForeground(new java.awt.Color(0, 0, 204));
        jLabelTimkiem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconsearch.png"))); // NOI18N
        jLabelTimkiem1.setText("Tìm kiếm:");
        jPanelInforGialichchieu.add(jLabelTimkiem1);
        jLabelTimkiem1.setBounds(11, 12, 100, 31);

        jTextFieldTimkiem1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldTimkiem1.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforGialichchieu.add(jTextFieldTimkiem1);
        jTextFieldTimkiem1.setBounds(115, 12, 126, 31);

        jLabelMagia.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelMagia.setForeground(new java.awt.Color(0, 0, 204));
        jLabelMagia.setText("Mã giá:");
        jPanelInforGialichchieu.add(jLabelMagia);
        jLabelMagia.setBounds(11, 54, 49, 22);

        jComboBoxTenloaithe.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jComboBoxTenloaithe.setForeground(new java.awt.Color(0, 0, 204));
        jComboBoxTenloaithe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanelInforGialichchieu.add(jComboBoxTenloaithe);
        jComboBoxTenloaithe.setBounds(125, 83, 127, 23);

        jTableQLGialichchieu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTableQLGialichchieu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTableQLGialichchieu.setForeground(new java.awt.Color(0, 0, 204));
        jTableQLGialichchieu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneBangGialichchieu.setViewportView(jTableQLGialichchieu);

        jPanelInforGialichchieu.add(jScrollPaneBangGialichchieu);
        jScrollPaneBangGialichchieu.setBounds(310, 0, 340, 260);

        jPanelQLGialichchieu.add(jPanelInforGialichchieu);
        jPanelInforGialichchieu.setBounds(80, 70, 650, 260);

        jLabelBackground1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBackground1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/image16.jpg"))); // NOI18N
        jPanelQLGialichchieu.add(jLabelBackground1);
        jLabelBackground1.setBounds(0, 0, 810, 410);

        jTabbedPane1.addTab("QL Giá lịch chiếu", jPanelQLGialichchieu);

        jPanelQLVe.setLayout(null);

        jLabelQLVe.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabelQLVe.setForeground(new java.awt.Color(255, 0, 0));
        jLabelQLVe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelQLVe.setText("Quản lý Vé");
        jPanelQLVe.add(jLabelQLVe);
        jLabelQLVe.setBounds(290, 10, 240, 40);

        jButtonBack2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonBack2.setForeground(new java.awt.Color(0, 0, 204));
        jButtonBack2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconback.png"))); // NOI18N
        jButtonBack2.setText("Back");
        jPanelQLVe.add(jButtonBack2);
        jButtonBack2.setBounds(10, 353, 107, 40);

        jButtonNext2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonNext2.setForeground(new java.awt.Color(0, 0, 204));
        jButtonNext2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconnext.png"))); // NOI18N
        jButtonNext2.setText("Next");
        jPanelQLVe.add(jButtonNext2);
        jButtonNext2.setBounds(127, 353, 105, 40);

        jButtonThem2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonThem2.setForeground(new java.awt.Color(0, 0, 204));
        jButtonThem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconadd.png"))); // NOI18N
        jButtonThem2.setText("Thêm");
        jButtonThem2.setBorder(null);
        jButtonThem2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonThem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThem2ActionPerformed(evt);
            }
        });
        jPanelQLVe.add(jButtonThem2);
        jButtonThem2.setBounds(242, 353, 102, 40);

        jButtonSua2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonSua2.setForeground(new java.awt.Color(0, 0, 204));
        jButtonSua2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconsua.png"))); // NOI18N
        jButtonSua2.setText("Sửa");
        jButtonSua2.setBorder(null);
        jButtonSua2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelQLVe.add(jButtonSua2);
        jButtonSua2.setBounds(354, 353, 88, 40);

        jButtonXoa2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonXoa2.setForeground(new java.awt.Color(0, 0, 204));
        jButtonXoa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconxoa.png"))); // NOI18N
        jButtonXoa2.setText("Xóa");
        jButtonXoa2.setBorder(null);
        jButtonXoa2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelQLVe.add(jButtonXoa2);
        jButtonXoa2.setBounds(458, 353, 91, 40);

        jButtonLuu2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonLuu2.setForeground(new java.awt.Color(0, 0, 204));
        jButtonLuu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconsave.png"))); // NOI18N
        jButtonLuu2.setText("Lưu");
        jButtonLuu2.setBorder(null);
        jButtonLuu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelQLVe.add(jButtonLuu2);
        jButtonLuu2.setBounds(559, 353, 88, 40);

        jButtonTrangchu2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonTrangchu2.setForeground(new java.awt.Color(0, 0, 204));
        jButtonTrangchu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconmenu.png"))); // NOI18N
        jButtonTrangchu2.setText("Trang chủ");
        jButtonTrangchu2.setBorder(null);
        jButtonTrangchu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelQLVe.add(jButtonTrangchu2);
        jButtonTrangchu2.setBounds(657, 353, 139, 40);

        jPanelInforVe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelInforVe.setLayout(null);

        jLabelMalichchieu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelMalichchieu.setForeground(new java.awt.Color(0, 0, 204));
        jLabelMalichchieu.setText("Mã lịch chiếu:");
        jPanelInforVe.add(jLabelMalichchieu);
        jLabelMalichchieu.setBounds(10, 120, 79, 22);

        jTextFieldMave.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldMave.setForeground(new java.awt.Color(0, 0, 204));
        jTextFieldMave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMaveActionPerformed(evt);
            }
        });
        jPanelInforVe.add(jTextFieldMave);
        jTextFieldMave.setBounds(80, 60, 107, 23);

        jTextFieldMalichchieu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldMalichchieu.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforVe.add(jTextFieldMalichchieu);
        jTextFieldMalichchieu.setBounds(100, 120, 107, 23);

        jLabelMakhuyenmai.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelMakhuyenmai.setForeground(new java.awt.Color(0, 0, 204));
        jLabelMakhuyenmai.setText("Mã khuyến mãi:");
        jPanelInforVe.add(jLabelMakhuyenmai);
        jLabelMakhuyenmai.setBounds(150, 150, 92, 22);

        jLabelMaghe.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelMaghe.setForeground(new java.awt.Color(0, 0, 204));
        jLabelMaghe.setText("Mã ghế:");
        jPanelInforVe.add(jLabelMaghe);
        jLabelMaghe.setBounds(10, 150, 60, 22);

        jLabelManhanvien.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelManhanvien.setForeground(new java.awt.Color(0, 0, 204));
        jLabelManhanvien.setText("Mã nhân viên:");
        jPanelInforVe.add(jLabelManhanvien);
        jLabelManhanvien.setBounds(10, 240, 79, 22);

        jTextFieldMakhuyenmai.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldMakhuyenmai.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforVe.add(jTextFieldMakhuyenmai);
        jTextFieldMakhuyenmai.setBounds(250, 150, 84, 23);

        jLabelMaKH.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelMaKH.setForeground(new java.awt.Color(0, 0, 204));
        jLabelMaKH.setText("Mã khách hàng:");
        jPanelInforVe.add(jLabelMaKH);
        jLabelMaKH.setBounds(10, 90, 90, 22);

        jTextFieldManhanvien.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldManhanvien.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforVe.add(jTextFieldManhanvien);
        jTextFieldManhanvien.setBounds(100, 240, 89, 23);

        jLabelTongtien.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelTongtien.setForeground(new java.awt.Color(0, 0, 204));
        jLabelTongtien.setText("Tổng tiền:");
        jPanelInforVe.add(jLabelTongtien);
        jLabelTongtien.setBounds(10, 210, 57, 22);

        jTextFieldThoidiemxuatve.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldThoidiemxuatve.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforVe.add(jTextFieldThoidiemxuatve);
        jTextFieldThoidiemxuatve.setBounds(380, 180, 73, 23);

        jLabelNgãyuatve.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelNgãyuatve.setForeground(new java.awt.Color(0, 0, 204));
        jLabelNgãyuatve.setText("Ngày xuất vé:");
        jPanelInforVe.add(jLabelNgãyuatve);
        jLabelNgãyuatve.setBounds(10, 180, 109, 22);

        jTextFieldMaghe.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldMaghe.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforVe.add(jTextFieldMaghe);
        jTextFieldMaghe.setBounds(80, 150, 59, 23);

        jLabelDiemtichluy.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelDiemtichluy.setForeground(new java.awt.Color(0, 0, 204));
        jLabelDiemtichluy.setText("Điểm tích lũy:");
        jPanelInforVe.add(jLabelDiemtichluy);
        jLabelDiemtichluy.setBounds(170, 210, 79, 22);

        jLabelThoidiemxuatve.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelThoidiemxuatve.setForeground(new java.awt.Color(0, 0, 204));
        jLabelThoidiemxuatve.setText("Thời điểm xuất vé:");
        jPanelInforVe.add(jLabelThoidiemxuatve);
        jLabelThoidiemxuatve.setBounds(270, 180, 109, 22);

        jDateChooserNgayxuatve.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforVe.add(jDateChooserNgayxuatve);
        jDateChooserNgayxuatve.setBounds(120, 180, 126, 22);

        jLabelTimkiem2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelTimkiem2.setForeground(new java.awt.Color(0, 0, 204));
        jLabelTimkiem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconsearch.png"))); // NOI18N
        jLabelTimkiem2.setText("Tìm kiếm:");
        jPanelInforVe.add(jLabelTimkiem2);
        jLabelTimkiem2.setBounds(11, 7, 100, 31);

        jTextFieldTimkiem2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldTimkiem2.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforVe.add(jTextFieldTimkiem2);
        jTextFieldTimkiem2.setBounds(115, 7, 126, 31);

        jLabelMave.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelMave.setForeground(new java.awt.Color(0, 0, 204));
        jLabelMave.setText("Mã vé:");
        jPanelInforVe.add(jLabelMave);
        jLabelMave.setBounds(10, 60, 46, 22);

        jTextFieldTongtien.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldTongtien.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforVe.add(jTextFieldTongtien);
        jTextFieldTongtien.setBounds(80, 210, 74, 23);

        jTextFieldDiemtichluy.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldDiemtichluy.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforVe.add(jTextFieldDiemtichluy);
        jTextFieldDiemtichluy.setBounds(260, 210, 78, 23);

        jTextFieldMaKH.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldMaKH.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforVe.add(jTextFieldMaKH);
        jTextFieldMaKH.setBounds(110, 90, 107, 23);

        jTableQLVe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTableQLVe.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTableQLVe.setForeground(new java.awt.Color(0, 0, 204));
        jTableQLVe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneBangVe.setViewportView(jTableQLVe);

        jPanelInforVe.add(jScrollPaneBangVe);
        jScrollPaneBangVe.setBounds(370, 0, 400, 160);

        jPanelQLVe.add(jPanelInforVe);
        jPanelInforVe.setBounds(20, 60, 770, 280);

        jLabelBackground2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBackground2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/image15.png"))); // NOI18N
        jPanelQLVe.add(jLabelBackground2);
        jLabelBackground2.setBounds(0, 0, 810, 410);

        jTabbedPane1.addTab("QL Vé", jPanelQLVe);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 40, 820, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_jLabelMinimizeMouseClicked

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jButtonThem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThem1ActionPerformed

    }//GEN-LAST:event_jButtonThem1ActionPerformed

    private void jButtonThem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThem2ActionPerformed

    }//GEN-LAST:event_jButtonThem2ActionPerformed

    private void jTextFieldMa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMa1ActionPerformed

    private void jTextFieldMaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormQLGiave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormQLGiave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormQLGiave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormQLGiave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormQLGiave().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack1;
    private javax.swing.JButton jButtonBack2;
    private javax.swing.JButton jButtonLuu1;
    private javax.swing.JButton jButtonLuu2;
    private javax.swing.JButton jButtonNext1;
    private javax.swing.JButton jButtonNext2;
    private javax.swing.JButton jButtonSua1;
    private javax.swing.JButton jButtonSua2;
    private javax.swing.JButton jButtonThem1;
    private javax.swing.JButton jButtonThem2;
    private javax.swing.JButton jButtonTrangchu1;
    private javax.swing.JButton jButtonTrangchu2;
    private javax.swing.JButton jButtonXoa1;
    private javax.swing.JButton jButtonXoa2;
    private javax.swing.JComboBox<String> jComboBoxTenloaithe;
    private com.toedter.calendar.JDateChooser jDateChooserNgayxuatve;
    private javax.swing.JLabel jLabelBackground1;
    private javax.swing.JLabel jLabelBackground2;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelDiemtichluy;
    private javax.swing.JLabel jLabelHeader;
    private javax.swing.JLabel jLabelMaKH;
    private javax.swing.JLabel jLabelMaghe;
    private javax.swing.JLabel jLabelMagia;
    private javax.swing.JLabel jLabelMakhuyenmai;
    private javax.swing.JLabel jLabelMalichchieu;
    private javax.swing.JLabel jLabelManhanvien;
    private javax.swing.JLabel jLabelMave;
    private javax.swing.JLabel jLabelMinimize;
    private javax.swing.JLabel jLabelNgãyuatve;
    private javax.swing.JLabel jLabelQLGialichchieu;
    private javax.swing.JLabel jLabelQLVe;
    private javax.swing.JLabel jLabelTenloaithe;
    private javax.swing.JLabel jLabelTgbatdau;
    private javax.swing.JLabel jLabelTgketthuc;
    private javax.swing.JLabel jLabelThoidiemxuatve;
    private javax.swing.JLabel jLabelThu;
    private javax.swing.JLabel jLabelTimkiem1;
    private javax.swing.JLabel jLabelTimkiem2;
    private javax.swing.JLabel jLabelTongtien;
    private javax.swing.JLabel jLabelTrigia;
    private javax.swing.JPanel jPanelInforGialichchieu;
    private javax.swing.JPanel jPanelInforVe;
    private javax.swing.JPanel jPanelQLGialichchieu;
    private javax.swing.JPanel jPanelQLVe;
    private javax.swing.JScrollPane jScrollPaneBangGialichchieu;
    private javax.swing.JScrollPane jScrollPaneBangVe;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableQLGialichchieu;
    private javax.swing.JTable jTableQLVe;
    private javax.swing.JTextField jTextFieldDiemtichluy;
    private javax.swing.JTextField jTextFieldMa1;
    private javax.swing.JTextField jTextFieldMaKH;
    private javax.swing.JTextField jTextFieldMaghe;
    private javax.swing.JTextField jTextFieldMakhuyenmai;
    private javax.swing.JTextField jTextFieldMalichchieu;
    private javax.swing.JTextField jTextFieldManhanvien;
    private javax.swing.JTextField jTextFieldMave;
    private javax.swing.JTextField jTextFieldTgbatdau;
    private javax.swing.JTextField jTextFieldTgketthuc;
    private javax.swing.JTextField jTextFieldThoidiemxuatve;
    private javax.swing.JTextField jTextFieldThu;
    private javax.swing.JTextField jTextFieldTimkiem1;
    private javax.swing.JTextField jTextFieldTimkiem2;
    private javax.swing.JTextField jTextFieldTongtien;
    private javax.swing.JTextField jTextFieldTrigia;
    // End of variables declaration//GEN-END:variables
}
