/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author ~Midori Mato~
 */
public class FormQLPhim extends javax.swing.JFrame {

    /**
     * Creates new form FormQLPhim
     */
    public FormQLPhim() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelHeader = new javax.swing.JLabel();
        jLabelMinimize = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jTabbedPaneQLPhim = new javax.swing.JTabbedPane();
        jPanelQLPhim = new javax.swing.JPanel();
        jLabelQuanlyPhim = new javax.swing.JLabel();
        jButtonBack1 = new javax.swing.JButton();
        jButtonNext1 = new javax.swing.JButton();
        jButtonThem1 = new javax.swing.JButton();
        jButtonSua1 = new javax.swing.JButton();
        jButtonXoa1 = new javax.swing.JButton();
        jButtonLuu1 = new javax.swing.JButton();
        jButtonTrangchu1 = new javax.swing.JButton();
        jPanelInforPhim = new javax.swing.JPanel();
        jLabelTen1 = new javax.swing.JLabel();
        jTextFieldMa1 = new javax.swing.JTextField();
        jTextFieldTen1 = new javax.swing.JTextField();
        jLabelGioihantuoi = new javax.swing.JLabel();
        jLabelQuocgia = new javax.swing.JLabel();
        jLabelNhasanxuat = new javax.swing.JLabel();
        jTextFieldNhasanxuat = new javax.swing.JTextField();
        jLabelDienvien = new javax.swing.JLabel();
        jTextFieldĐinhang = new javax.swing.JTextField();
        jLabelThoiluong = new javax.swing.JLabel();
        jTextFieldDienvien = new javax.swing.JTextField();
        jLabelNoidung = new javax.swing.JLabel();
        jTextFieldNoidung = new javax.swing.JTextField();
        jLabelTimkiem1 = new javax.swing.JLabel();
        jTextFieldTimkiem1 = new javax.swing.JTextField();
        jLabelMa1 = new javax.swing.JLabel();
        jSpinnerGioihantuoi = new javax.swing.JSpinner();
        jComboBoxQuocgia = new javax.swing.JComboBox<>();
        jLabelNgaykhoichieu = new javax.swing.JLabel();
        jDateChooserNgaykhoichieu = new com.toedter.calendar.JDateChooser();
        jLabelDinhdang = new javax.swing.JLabel();
        jTextFieldThoiluong = new javax.swing.JTextField();
        jScrollPaneBangPhim = new javax.swing.JScrollPane();
        jTableQLPhim = new javax.swing.JTable();
        jLabelBackground1 = new javax.swing.JLabel();
        jPanelQLDinhdang = new javax.swing.JPanel();
        jLabelQuanlyKH1 = new javax.swing.JLabel();
        jButtonBack2 = new javax.swing.JButton();
        jButtonNext2 = new javax.swing.JButton();
        jButtonThem2 = new javax.swing.JButton();
        jButtonSua2 = new javax.swing.JButton();
        jButtonXoa2 = new javax.swing.JButton();
        jButtonLuu2 = new javax.swing.JButton();
        jButtonTrangchu2 = new javax.swing.JButton();
        jPanelInforPhim1 = new javax.swing.JPanel();
        jLabelTen2 = new javax.swing.JLabel();
        jTextFieldMa2 = new javax.swing.JTextField();
        jTextFieldTen2 = new javax.swing.JTextField();
        jLabelPhuthu = new javax.swing.JLabel();
        jLabelTimkiem2 = new javax.swing.JLabel();
        jTextFieldTimkiem2 = new javax.swing.JTextField();
        jLabelMa2 = new javax.swing.JLabel();
        jTextFieldPhuthu = new javax.swing.JTextField();
        jScrollPaneBangPhim1 = new javax.swing.JScrollPane();
        jTableQLPhim1 = new javax.swing.JTable();
        jLabelBackground2 = new javax.swing.JLabel();
        jPanel1QLPhimDinhdang = new javax.swing.JPanel();
        jLabelQLPhimDinhdang = new javax.swing.JLabel();
        jButtonBack3 = new javax.swing.JButton();
        jButtonNext3 = new javax.swing.JButton();
        jButtonThem3 = new javax.swing.JButton();
        jButtonSua3 = new javax.swing.JButton();
        jButtonXoa3 = new javax.swing.JButton();
        jButtonLuu3 = new javax.swing.JButton();
        jButtonTrangchu3 = new javax.swing.JButton();
        jPanelInforPhimDinhdang = new javax.swing.JPanel();
        jLabelMadinhdang = new javax.swing.JLabel();
        jTextFieldMaphim = new javax.swing.JTextField();
        jTextFieldMadinhdang = new javax.swing.JTextField();
        jLabelTimkiem3 = new javax.swing.JLabel();
        jTextFieldTimkiem3 = new javax.swing.JTextField();
        jLabelMaphi = new javax.swing.JLabel();
        jScrollPaneBangPhimDinhdang = new javax.swing.JScrollPane();
        jTableQLPhimDinhdang = new javax.swing.JTable();
        jLabelBackground3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(820, 478));
        setResizable(false);
        setSize(new java.awt.Dimension(820, 478));
        getContentPane().setLayout(null);

        jLabelHeader.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelHeader.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/image0.png"))); // NOI18N
        getContentPane().add(jLabelHeader);
        jLabelHeader.setBounds(0, 0, 820, 40);

        jLabelMinimize.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelMinimize);
        jLabelMinimize.setBounds(710, 0, 50, 40);

        jLabelClose.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelClose);
        jLabelClose.setBounds(770, 0, 50, 40);

        jTabbedPaneQLPhim.setForeground(new java.awt.Color(0, 0, 204));

        jPanelQLPhim.setLayout(null);

        jLabelQuanlyPhim.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabelQuanlyPhim.setForeground(new java.awt.Color(255, 0, 0));
        jLabelQuanlyPhim.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelQuanlyPhim.setText("Quản lý Phim");
        jPanelQLPhim.add(jLabelQuanlyPhim);
        jLabelQuanlyPhim.setBounds(285, 4, 259, 40);

        jButtonBack1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonBack1.setForeground(new java.awt.Color(0, 0, 204));
        jButtonBack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconback.png"))); // NOI18N
        jButtonBack1.setText("Back");
        jPanelQLPhim.add(jButtonBack1);
        jButtonBack1.setBounds(20, 360, 107, 40);

        jButtonNext1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonNext1.setForeground(new java.awt.Color(0, 0, 204));
        jButtonNext1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconnext.png"))); // NOI18N
        jButtonNext1.setText("Next");
        jPanelQLPhim.add(jButtonNext1);
        jButtonNext1.setBounds(130, 360, 105, 40);

        jButtonThem1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonThem1.setForeground(new java.awt.Color(0, 0, 204));
        jButtonThem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconadd.png"))); // NOI18N
        jButtonThem1.setText("Thêm");
        jButtonThem1.setBorder(null);
        jButtonThem1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonThem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThem1ActionPerformed(evt);
            }
        });
        jPanelQLPhim.add(jButtonThem1);
        jButtonThem1.setBounds(250, 360, 102, 40);

        jButtonSua1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonSua1.setForeground(new java.awt.Color(0, 0, 204));
        jButtonSua1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconsua.png"))); // NOI18N
        jButtonSua1.setText("Sửa");
        jButtonSua1.setBorder(null);
        jButtonSua1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelQLPhim.add(jButtonSua1);
        jButtonSua1.setBounds(360, 360, 88, 40);

        jButtonXoa1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonXoa1.setForeground(new java.awt.Color(0, 0, 204));
        jButtonXoa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconxoa.png"))); // NOI18N
        jButtonXoa1.setText("Xóa");
        jButtonXoa1.setBorder(null);
        jButtonXoa1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelQLPhim.add(jButtonXoa1);
        jButtonXoa1.setBounds(470, 360, 91, 40);

        jButtonLuu1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonLuu1.setForeground(new java.awt.Color(0, 0, 204));
        jButtonLuu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconsave.png"))); // NOI18N
        jButtonLuu1.setText("Lưu");
        jButtonLuu1.setBorder(null);
        jButtonLuu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelQLPhim.add(jButtonLuu1);
        jButtonLuu1.setBounds(570, 360, 88, 40);

        jButtonTrangchu1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonTrangchu1.setForeground(new java.awt.Color(0, 0, 204));
        jButtonTrangchu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconmenu.png"))); // NOI18N
        jButtonTrangchu1.setText("Trang chủ");
        jButtonTrangchu1.setBorder(null);
        jButtonTrangchu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelQLPhim.add(jButtonTrangchu1);
        jButtonTrangchu1.setBounds(660, 360, 139, 40);

        jPanelInforPhim.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelInforPhim.setLayout(null);

        jLabelTen1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelTen1.setForeground(new java.awt.Color(0, 0, 204));
        jLabelTen1.setText("Tên phim:");
        jPanelInforPhim.add(jLabelTen1);
        jLabelTen1.setBounds(11, 78, 65, 22);

        jTextFieldMa1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldMa1.setForeground(new java.awt.Color(0, 0, 204));
        jTextFieldMa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMa1ActionPerformed(evt);
            }
        });
        jPanelInforPhim.add(jTextFieldMa1);
        jTextFieldMa1.setBounds(98, 49, 107, 23);

        jTextFieldTen1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldTen1.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforPhim.add(jTextFieldTen1);
        jTextFieldTen1.setBounds(98, 78, 218, 23);

        jLabelGioihantuoi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelGioihantuoi.setForeground(new java.awt.Color(0, 0, 204));
        jLabelGioihantuoi.setText("Giới hạn tuổi:");
        jPanelInforPhim.add(jLabelGioihantuoi);
        jLabelGioihantuoi.setBounds(11, 107, 83, 22);

        jLabelQuocgia.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelQuocgia.setForeground(new java.awt.Color(0, 0, 204));
        jLabelQuocgia.setText("Quốc gia:");
        jPanelInforPhim.add(jLabelQuocgia);
        jLabelQuocgia.setBounds(164, 107, 54, 22);

        jLabelNhasanxuat.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelNhasanxuat.setForeground(new java.awt.Color(0, 0, 204));
        jLabelNhasanxuat.setText("Nhà sản suất:");
        jPanelInforPhim.add(jLabelNhasanxuat);
        jLabelNhasanxuat.setBounds(11, 136, 79, 22);

        jTextFieldNhasanxuat.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldNhasanxuat.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforPhim.add(jTextFieldNhasanxuat);
        jTextFieldNhasanxuat.setBounds(100, 136, 76, 23);

        jLabelDienvien.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelDienvien.setForeground(new java.awt.Color(0, 0, 204));
        jLabelDienvien.setText("Diễn viên:");
        jPanelInforPhim.add(jLabelDienvien);
        jLabelDienvien.setBounds(11, 194, 79, 22);

        jTextFieldĐinhang.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldĐinhang.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforPhim.add(jTextFieldĐinhang);
        jTextFieldĐinhang.setBounds(261, 136, 82, 23);

        jLabelThoiluong.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelThoiluong.setForeground(new java.awt.Color(0, 0, 204));
        jLabelThoiluong.setText("Thời lượng:");
        jPanelInforPhim.add(jLabelThoiluong);
        jLabelThoiluong.setBounds(11, 165, 79, 22);

        jTextFieldDienvien.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldDienvien.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforPhim.add(jTextFieldDienvien);
        jTextFieldDienvien.setBounds(100, 194, 164, 23);

        jLabelNoidung.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelNoidung.setForeground(new java.awt.Color(0, 0, 204));
        jLabelNoidung.setText("Nội dung:");
        jPanelInforPhim.add(jLabelNoidung);
        jLabelNoidung.setBounds(282, 194, 57, 22);

        jTextFieldNoidung.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldNoidung.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforPhim.add(jTextFieldNoidung);
        jTextFieldNoidung.setBounds(349, 194, 394, 52);

        jLabelTimkiem1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelTimkiem1.setForeground(new java.awt.Color(0, 0, 204));
        jLabelTimkiem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconsearch.png"))); // NOI18N
        jLabelTimkiem1.setText("Tìm kiếm:");
        jPanelInforPhim.add(jLabelTimkiem1);
        jLabelTimkiem1.setBounds(11, 12, 100, 31);

        jTextFieldTimkiem1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldTimkiem1.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforPhim.add(jTextFieldTimkiem1);
        jTextFieldTimkiem1.setBounds(111, 11, 126, 31);

        jLabelMa1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelMa1.setForeground(new java.awt.Color(0, 0, 204));
        jLabelMa1.setText("Mã phim:");
        jPanelInforPhim.add(jLabelMa1);
        jLabelMa1.setBounds(11, 49, 65, 22);

        jSpinnerGioihantuoi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanelInforPhim.add(jSpinnerGioihantuoi);
        jSpinnerGioihantuoi.setBounds(98, 108, 39, 22);

        jComboBoxQuocgia.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jComboBoxQuocgia.setForeground(new java.awt.Color(0, 0, 204));
        jComboBoxQuocgia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanelInforPhim.add(jComboBoxQuocgia);
        jComboBoxQuocgia.setBounds(228, 107, 75, 23);

        jLabelNgaykhoichieu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelNgaykhoichieu.setForeground(new java.awt.Color(0, 0, 204));
        jLabelNgaykhoichieu.setText("Ngày khởi chiếu:");
        jPanelInforPhim.add(jLabelNgaykhoichieu);
        jLabelNgaykhoichieu.setBounds(185, 168, 95, 17);

        jDateChooserNgaykhoichieu.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforPhim.add(jDateChooserNgaykhoichieu);
        jDateChooserNgaykhoichieu.setBounds(284, 165, 136, 22);

        jLabelDinhdang.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelDinhdang.setForeground(new java.awt.Color(0, 0, 204));
        jLabelDinhdang.setText("Định dạng:");
        jPanelInforPhim.add(jLabelDinhdang);
        jLabelDinhdang.setBounds(186, 139, 71, 17);

        jTextFieldThoiluong.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldThoiluong.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforPhim.add(jTextFieldThoiluong);
        jTextFieldThoiluong.setBounds(100, 165, 75, 23);

        jTableQLPhim.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTableQLPhim.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTableQLPhim.setForeground(new java.awt.Color(0, 0, 204));
        jTableQLPhim.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneBangPhim.setViewportView(jTableQLPhim);

        jPanelInforPhim.add(jScrollPaneBangPhim);
        jScrollPaneBangPhim.setBounds(370, 0, 410, 150);

        jPanelQLPhim.add(jPanelInforPhim);
        jPanelInforPhim.setBounds(20, 70, 780, 280);

        jLabelBackground1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBackground1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/image17.png"))); // NOI18N
        jPanelQLPhim.add(jLabelBackground1);
        jLabelBackground1.setBounds(0, 0, 820, 410);

        jTabbedPaneQLPhim.addTab("QL Phim", jPanelQLPhim);

        jPanelQLDinhdang.setLayout(null);

        jLabelQuanlyKH1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabelQuanlyKH1.setForeground(new java.awt.Color(255, 0, 0));
        jLabelQuanlyKH1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelQuanlyKH1.setText("Quản lý Định dạng phim");
        jPanelQLDinhdang.add(jLabelQuanlyKH1);
        jLabelQuanlyKH1.setBounds(210, 10, 400, 50);

        jButtonBack2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonBack2.setForeground(new java.awt.Color(0, 0, 204));
        jButtonBack2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconback.png"))); // NOI18N
        jButtonBack2.setText("Back");
        jPanelQLDinhdang.add(jButtonBack2);
        jButtonBack2.setBounds(10, 353, 107, 40);

        jButtonNext2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonNext2.setForeground(new java.awt.Color(0, 0, 204));
        jButtonNext2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconnext.png"))); // NOI18N
        jButtonNext2.setText("Next");
        jPanelQLDinhdang.add(jButtonNext2);
        jButtonNext2.setBounds(127, 353, 105, 40);

        jButtonThem2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonThem2.setForeground(new java.awt.Color(0, 0, 204));
        jButtonThem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconadd.png"))); // NOI18N
        jButtonThem2.setText("Thêm");
        jButtonThem2.setBorder(null);
        jButtonThem2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonThem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThem2ActionPerformed(evt);
            }
        });
        jPanelQLDinhdang.add(jButtonThem2);
        jButtonThem2.setBounds(242, 353, 102, 40);

        jButtonSua2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonSua2.setForeground(new java.awt.Color(0, 0, 204));
        jButtonSua2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconsua.png"))); // NOI18N
        jButtonSua2.setText("Sửa");
        jButtonSua2.setBorder(null);
        jButtonSua2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelQLDinhdang.add(jButtonSua2);
        jButtonSua2.setBounds(354, 353, 88, 40);

        jButtonXoa2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonXoa2.setForeground(new java.awt.Color(0, 0, 204));
        jButtonXoa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconxoa.png"))); // NOI18N
        jButtonXoa2.setText("Xóa");
        jButtonXoa2.setBorder(null);
        jButtonXoa2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelQLDinhdang.add(jButtonXoa2);
        jButtonXoa2.setBounds(458, 353, 91, 40);

        jButtonLuu2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonLuu2.setForeground(new java.awt.Color(0, 0, 204));
        jButtonLuu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconsave.png"))); // NOI18N
        jButtonLuu2.setText("Lưu");
        jButtonLuu2.setBorder(null);
        jButtonLuu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelQLDinhdang.add(jButtonLuu2);
        jButtonLuu2.setBounds(559, 353, 88, 40);

        jButtonTrangchu2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonTrangchu2.setForeground(new java.awt.Color(0, 0, 204));
        jButtonTrangchu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconmenu.png"))); // NOI18N
        jButtonTrangchu2.setText("Trang chủ");
        jButtonTrangchu2.setBorder(null);
        jButtonTrangchu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelQLDinhdang.add(jButtonTrangchu2);
        jButtonTrangchu2.setBounds(657, 353, 139, 40);

        jPanelInforPhim1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelInforPhim1.setLayout(null);

        jLabelTen2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelTen2.setForeground(new java.awt.Color(0, 0, 204));
        jLabelTen2.setText("Tên định dạng:");
        jPanelInforPhim1.add(jLabelTen2);
        jLabelTen2.setBounds(11, 111, 100, 22);

        jTextFieldMa2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldMa2.setForeground(new java.awt.Color(0, 0, 204));
        jTextFieldMa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMa2ActionPerformed(evt);
            }
        });
        jPanelInforPhim1.add(jTextFieldMa2);
        jTextFieldMa2.setBounds(129, 78, 107, 23);

        jTextFieldTen2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldTen2.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforPhim1.add(jTextFieldTen2);
        jTextFieldTen2.setBounds(129, 111, 110, 23);

        jLabelPhuthu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelPhuthu.setForeground(new java.awt.Color(0, 0, 204));
        jLabelPhuthu.setText("Phụ thu định dạng:");
        jPanelInforPhim1.add(jLabelPhuthu);
        jLabelPhuthu.setBounds(11, 145, 119, 22);

        jLabelTimkiem2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelTimkiem2.setForeground(new java.awt.Color(0, 0, 204));
        jLabelTimkiem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconsearch.png"))); // NOI18N
        jLabelTimkiem2.setText("Tìm kiếm:");
        jPanelInforPhim1.add(jLabelTimkiem2);
        jLabelTimkiem2.setBounds(11, 12, 100, 31);

        jTextFieldTimkiem2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldTimkiem2.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforPhim1.add(jTextFieldTimkiem2);
        jTextFieldTimkiem2.setBounds(111, 11, 126, 31);

        jLabelMa2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelMa2.setForeground(new java.awt.Color(0, 0, 204));
        jLabelMa2.setText("Mã định dạng:");
        jPanelInforPhim1.add(jLabelMa2);
        jLabelMa2.setBounds(11, 78, 100, 22);

        jTextFieldPhuthu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldPhuthu.setForeground(new java.awt.Color(0, 0, 204));
        jTextFieldPhuthu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPhuthuActionPerformed(evt);
            }
        });
        jPanelInforPhim1.add(jTextFieldPhuthu);
        jTextFieldPhuthu.setBounds(129, 145, 107, 23);

        jTableQLPhim1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTableQLPhim1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTableQLPhim1.setForeground(new java.awt.Color(0, 0, 204));
        jTableQLPhim1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneBangPhim1.setViewportView(jTableQLPhim1);

        jPanelInforPhim1.add(jScrollPaneBangPhim1);
        jScrollPaneBangPhim1.setBounds(300, 0, 310, 260);

        jPanelQLDinhdang.add(jPanelInforPhim1);
        jPanelInforPhim1.setBounds(100, 70, 610, 260);

        jLabelBackground2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBackground2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/image4.jpg"))); // NOI18N
        jPanelQLDinhdang.add(jLabelBackground2);
        jLabelBackground2.setBounds(0, 0, 820, 410);

        jTabbedPaneQLPhim.addTab("QL Định dạng phim", jPanelQLDinhdang);

        jPanel1QLPhimDinhdang.setLayout(null);

        jLabelQLPhimDinhdang.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabelQLPhimDinhdang.setForeground(new java.awt.Color(255, 0, 0));
        jLabelQLPhimDinhdang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelQLPhimDinhdang.setText("Quản lý Phim - Định dạng phim");
        jPanel1QLPhimDinhdang.add(jLabelQLPhimDinhdang);
        jLabelQLPhimDinhdang.setBounds(140, 10, 540, 50);

        jButtonBack3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonBack3.setForeground(new java.awt.Color(0, 0, 204));
        jButtonBack3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconback.png"))); // NOI18N
        jButtonBack3.setText("Back");
        jPanel1QLPhimDinhdang.add(jButtonBack3);
        jButtonBack3.setBounds(10, 353, 107, 40);

        jButtonNext3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonNext3.setForeground(new java.awt.Color(0, 0, 204));
        jButtonNext3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconnext.png"))); // NOI18N
        jButtonNext3.setText("Next");
        jPanel1QLPhimDinhdang.add(jButtonNext3);
        jButtonNext3.setBounds(127, 353, 105, 40);

        jButtonThem3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonThem3.setForeground(new java.awt.Color(0, 0, 204));
        jButtonThem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconadd.png"))); // NOI18N
        jButtonThem3.setText("Thêm");
        jButtonThem3.setBorder(null);
        jButtonThem3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonThem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThem3ActionPerformed(evt);
            }
        });
        jPanel1QLPhimDinhdang.add(jButtonThem3);
        jButtonThem3.setBounds(242, 353, 102, 40);

        jButtonSua3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonSua3.setForeground(new java.awt.Color(0, 0, 204));
        jButtonSua3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconsua.png"))); // NOI18N
        jButtonSua3.setText("Sửa");
        jButtonSua3.setBorder(null);
        jButtonSua3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1QLPhimDinhdang.add(jButtonSua3);
        jButtonSua3.setBounds(354, 353, 88, 40);

        jButtonXoa3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonXoa3.setForeground(new java.awt.Color(0, 0, 204));
        jButtonXoa3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconxoa.png"))); // NOI18N
        jButtonXoa3.setText("Xóa");
        jButtonXoa3.setBorder(null);
        jButtonXoa3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1QLPhimDinhdang.add(jButtonXoa3);
        jButtonXoa3.setBounds(458, 353, 91, 40);

        jButtonLuu3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonLuu3.setForeground(new java.awt.Color(0, 0, 204));
        jButtonLuu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconsave.png"))); // NOI18N
        jButtonLuu3.setText("Lưu");
        jButtonLuu3.setBorder(null);
        jButtonLuu3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1QLPhimDinhdang.add(jButtonLuu3);
        jButtonLuu3.setBounds(559, 353, 88, 40);

        jButtonTrangchu3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonTrangchu3.setForeground(new java.awt.Color(0, 0, 204));
        jButtonTrangchu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconmenu.png"))); // NOI18N
        jButtonTrangchu3.setText("Trang chủ");
        jButtonTrangchu3.setBorder(null);
        jButtonTrangchu3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1QLPhimDinhdang.add(jButtonTrangchu3);
        jButtonTrangchu3.setBounds(657, 353, 139, 40);

        jPanelInforPhimDinhdang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelInforPhimDinhdang.setLayout(null);

        jLabelMadinhdang.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelMadinhdang.setForeground(new java.awt.Color(0, 0, 204));
        jLabelMadinhdang.setText("Mã định dạng:");
        jPanelInforPhimDinhdang.add(jLabelMadinhdang);
        jLabelMadinhdang.setBounds(11, 111, 92, 22);

        jTextFieldMaphim.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldMaphim.setForeground(new java.awt.Color(0, 0, 204));
        jTextFieldMaphim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMaphimActionPerformed(evt);
            }
        });
        jPanelInforPhimDinhdang.add(jTextFieldMaphim);
        jTextFieldMaphim.setBounds(129, 78, 107, 23);

        jTextFieldMadinhdang.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldMadinhdang.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforPhimDinhdang.add(jTextFieldMadinhdang);
        jTextFieldMadinhdang.setBounds(129, 111, 107, 23);

        jLabelTimkiem3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelTimkiem3.setForeground(new java.awt.Color(0, 0, 204));
        jLabelTimkiem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconsearch.png"))); // NOI18N
        jLabelTimkiem3.setText("Tìm kiếm:");
        jPanelInforPhimDinhdang.add(jLabelTimkiem3);
        jLabelTimkiem3.setBounds(11, 12, 100, 31);

        jTextFieldTimkiem3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldTimkiem3.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforPhimDinhdang.add(jTextFieldTimkiem3);
        jTextFieldTimkiem3.setBounds(111, 11, 126, 31);

        jLabelMaphi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelMaphi.setForeground(new java.awt.Color(0, 0, 204));
        jLabelMaphi.setText("Mã phim:");
        jPanelInforPhimDinhdang.add(jLabelMaphi);
        jLabelMaphi.setBounds(11, 78, 100, 22);

        jTableQLPhimDinhdang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTableQLPhimDinhdang.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTableQLPhimDinhdang.setForeground(new java.awt.Color(0, 0, 204));
        jTableQLPhimDinhdang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneBangPhimDinhdang.setViewportView(jTableQLPhimDinhdang);

        jPanelInforPhimDinhdang.add(jScrollPaneBangPhimDinhdang);
        jScrollPaneBangPhimDinhdang.setBounds(280, 0, 240, 260);

        jPanel1QLPhimDinhdang.add(jPanelInforPhimDinhdang);
        jPanelInforPhimDinhdang.setBounds(150, 80, 520, 260);

        jLabelBackground3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBackground3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/image2.jpg"))); // NOI18N
        jPanel1QLPhimDinhdang.add(jLabelBackground3);
        jLabelBackground3.setBounds(0, 0, 820, 410);

        jTabbedPaneQLPhim.addTab("QL Phim - Định dạng phim", jPanel1QLPhimDinhdang);

        getContentPane().add(jTabbedPaneQLPhim);
        jTabbedPaneQLPhim.setBounds(0, 40, 820, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_jLabelMinimizeMouseClicked

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jButtonThem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonThem1ActionPerformed

    private void jButtonThem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonThem2ActionPerformed

    private void jButtonThem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonThem3ActionPerformed

    private void jTextFieldMa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMa1ActionPerformed

    private void jTextFieldMa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMa2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMa2ActionPerformed

    private void jTextFieldPhuthuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPhuthuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPhuthuActionPerformed

    private void jTextFieldMaphimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMaphimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMaphimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormQLPhim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormQLPhim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormQLPhim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormQLPhim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormQLPhim().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack1;
    private javax.swing.JButton jButtonBack2;
    private javax.swing.JButton jButtonBack3;
    private javax.swing.JButton jButtonLuu1;
    private javax.swing.JButton jButtonLuu2;
    private javax.swing.JButton jButtonLuu3;
    private javax.swing.JButton jButtonNext1;
    private javax.swing.JButton jButtonNext2;
    private javax.swing.JButton jButtonNext3;
    private javax.swing.JButton jButtonSua1;
    private javax.swing.JButton jButtonSua2;
    private javax.swing.JButton jButtonSua3;
    private javax.swing.JButton jButtonThem1;
    private javax.swing.JButton jButtonThem2;
    private javax.swing.JButton jButtonThem3;
    private javax.swing.JButton jButtonTrangchu1;
    private javax.swing.JButton jButtonTrangchu2;
    private javax.swing.JButton jButtonTrangchu3;
    private javax.swing.JButton jButtonXoa1;
    private javax.swing.JButton jButtonXoa2;
    private javax.swing.JButton jButtonXoa3;
    private javax.swing.JComboBox<String> jComboBoxQuocgia;
    private com.toedter.calendar.JDateChooser jDateChooserNgaykhoichieu;
    private javax.swing.JLabel jLabelBackground1;
    private javax.swing.JLabel jLabelBackground2;
    private javax.swing.JLabel jLabelBackground3;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelDienvien;
    private javax.swing.JLabel jLabelDinhdang;
    private javax.swing.JLabel jLabelGioihantuoi;
    private javax.swing.JLabel jLabelHeader;
    private javax.swing.JLabel jLabelMa1;
    private javax.swing.JLabel jLabelMa2;
    private javax.swing.JLabel jLabelMadinhdang;
    private javax.swing.JLabel jLabelMaphi;
    private javax.swing.JLabel jLabelMinimize;
    private javax.swing.JLabel jLabelNgaykhoichieu;
    private javax.swing.JLabel jLabelNhasanxuat;
    private javax.swing.JLabel jLabelNoidung;
    private javax.swing.JLabel jLabelPhuthu;
    private javax.swing.JLabel jLabelQLPhimDinhdang;
    private javax.swing.JLabel jLabelQuanlyKH1;
    private javax.swing.JLabel jLabelQuanlyPhim;
    private javax.swing.JLabel jLabelQuocgia;
    private javax.swing.JLabel jLabelTen1;
    private javax.swing.JLabel jLabelTen2;
    private javax.swing.JLabel jLabelThoiluong;
    private javax.swing.JLabel jLabelTimkiem1;
    private javax.swing.JLabel jLabelTimkiem2;
    private javax.swing.JLabel jLabelTimkiem3;
    private javax.swing.JPanel jPanel1QLPhimDinhdang;
    private javax.swing.JPanel jPanelInforPhim;
    private javax.swing.JPanel jPanelInforPhim1;
    private javax.swing.JPanel jPanelInforPhimDinhdang;
    private javax.swing.JPanel jPanelQLDinhdang;
    private javax.swing.JPanel jPanelQLPhim;
    private javax.swing.JScrollPane jScrollPaneBangPhim;
    private javax.swing.JScrollPane jScrollPaneBangPhim1;
    private javax.swing.JScrollPane jScrollPaneBangPhimDinhdang;
    private javax.swing.JSpinner jSpinnerGioihantuoi;
    private javax.swing.JTabbedPane jTabbedPaneQLPhim;
    private javax.swing.JTable jTableQLPhim;
    private javax.swing.JTable jTableQLPhim1;
    private javax.swing.JTable jTableQLPhimDinhdang;
    private javax.swing.JTextField jTextFieldDienvien;
    private javax.swing.JTextField jTextFieldMa1;
    private javax.swing.JTextField jTextFieldMa2;
    private javax.swing.JTextField jTextFieldMadinhdang;
    private javax.swing.JTextField jTextFieldMaphim;
    private javax.swing.JTextField jTextFieldNhasanxuat;
    private javax.swing.JTextField jTextFieldNoidung;
    private javax.swing.JTextField jTextFieldPhuthu;
    private javax.swing.JTextField jTextFieldTen1;
    private javax.swing.JTextField jTextFieldTen2;
    private javax.swing.JTextField jTextFieldThoiluong;
    private javax.swing.JTextField jTextFieldTimkiem1;
    private javax.swing.JTextField jTextFieldTimkiem2;
    private javax.swing.JTextField jTextFieldTimkiem3;
    private javax.swing.JTextField jTextFieldĐinhang;
    // End of variables declaration//GEN-END:variables
}
