/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author ~Midori Mato~
 */
public class FormQLTaikhoan extends javax.swing.JFrame {

    /**
     * Creates new form FormQLTaikhoan
     */
    public FormQLTaikhoan() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelHeader = new javax.swing.JLabel();
        jLabelMinimize = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jTabbedPaneQLTaikhoan = new javax.swing.JTabbedPane();
        jPanelQLTaikhoan = new javax.swing.JPanel();
        jLabelQLTaikhoan = new javax.swing.JLabel();
        jButtonBack1 = new javax.swing.JButton();
        jButtonNext1 = new javax.swing.JButton();
        jButtonThem1 = new javax.swing.JButton();
        jButtonSua1 = new javax.swing.JButton();
        jButtonXoa1 = new javax.swing.JButton();
        jButtonLuu1 = new javax.swing.JButton();
        jButtonTrangchu1 = new javax.swing.JButton();
        jPanelInforTaikhoan = new javax.swing.JPanel();
        jLabelTenNV = new javax.swing.JLabel();
        jTextFieldMaNV = new javax.swing.JTextField();
        jTextFieldTenNV = new javax.swing.JTextField();
        jLabelMaquyen1 = new javax.swing.JLabel();
        jLabelMatkhau = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldMatkhau = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jLabelTimkiem1 = new javax.swing.JLabel();
        jTextFieldTimkiem1 = new javax.swing.JTextField();
        jComboBoxMaquyen = new javax.swing.JComboBox<>();
        jLabelMaNV = new javax.swing.JLabel();
        jScrollPaneBangTaikhoan = new javax.swing.JScrollPane();
        jTableQLTaikhoan = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanelQLQuyentruycap = new javax.swing.JPanel();
        jLabelQLQuyentruycap = new javax.swing.JLabel();
        jButtonBack2 = new javax.swing.JButton();
        jButtonNext2 = new javax.swing.JButton();
        jButtonThem2 = new javax.swing.JButton();
        jButtonSua2 = new javax.swing.JButton();
        jButtonXoa2 = new javax.swing.JButton();
        jButtonLuu2 = new javax.swing.JButton();
        jButtonTrangchu2 = new javax.swing.JButton();
        jPanelInforQuyentruycap = new javax.swing.JPanel();
        jLabelChucvu = new javax.swing.JLabel();
        jTextFieldMaquyen = new javax.swing.JTextField();
        jTextFieldChucvu = new javax.swing.JTextField();
        jLabelTimkiem2 = new javax.swing.JLabel();
        jTextFieldTimkiem2 = new javax.swing.JTextField();
        jLabelMaquyen2 = new javax.swing.JLabel();
        jLabelQuyen = new javax.swing.JLabel();
        jCheckBoxBanve = new javax.swing.JCheckBox();
        jCheckBoxQLKH = new javax.swing.JCheckBox();
        jCheckBoxDoimatkhau = new javax.swing.JCheckBox();
        jCheckBoxQLTK = new javax.swing.JCheckBox();
        jCheckBoxTracuu = new javax.swing.JCheckBox();
        jCheckBoxQLPhim = new javax.swing.JCheckBox();
        jCheckBoxQLPhongchieu = new javax.swing.JCheckBox();
        jCheckBoxQLLichchieu = new javax.swing.JCheckBox();
        jCheckBoxQLKhuyenmai = new javax.swing.JCheckBox();
        jCheckBoxQLGiave = new javax.swing.JCheckBox();
        jCheckBoxThongke = new javax.swing.JCheckBox();
        jScrollPaneBangQuyentruycap = new javax.swing.JScrollPane();
        jTableQLQuyentruycap = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(820, 478));
        setResizable(false);
        setSize(new java.awt.Dimension(820, 478));
        getContentPane().setLayout(null);

        jLabelHeader.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelHeader.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/image0.png"))); // NOI18N
        getContentPane().add(jLabelHeader);
        jLabelHeader.setBounds(0, 0, 820, 40);

        jLabelMinimize.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelMinimize);
        jLabelMinimize.setBounds(710, 0, 50, 40);

        jLabelClose.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelClose);
        jLabelClose.setBounds(770, 0, 50, 40);

        jTabbedPaneQLTaikhoan.setForeground(new java.awt.Color(0, 0, 204));

        jPanelQLTaikhoan.setLayout(null);

        jLabelQLTaikhoan.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabelQLTaikhoan.setForeground(new java.awt.Color(255, 0, 0));
        jLabelQLTaikhoan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelQLTaikhoan.setText("Quản lý Tài khoản");
        jPanelQLTaikhoan.add(jLabelQLTaikhoan);
        jLabelQLTaikhoan.setBounds(240, 10, 340, 40);

        jButtonBack1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonBack1.setForeground(new java.awt.Color(0, 0, 204));
        jButtonBack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconback.png"))); // NOI18N
        jButtonBack1.setText("Back");
        jPanelQLTaikhoan.add(jButtonBack1);
        jButtonBack1.setBounds(10, 363, 107, 40);

        jButtonNext1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonNext1.setForeground(new java.awt.Color(0, 0, 204));
        jButtonNext1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconnext.png"))); // NOI18N
        jButtonNext1.setText("Next");
        jPanelQLTaikhoan.add(jButtonNext1);
        jButtonNext1.setBounds(130, 363, 105, 40);

        jButtonThem1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonThem1.setForeground(new java.awt.Color(0, 0, 204));
        jButtonThem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconadd.png"))); // NOI18N
        jButtonThem1.setText("Thêm");
        jButtonThem1.setBorder(null);
        jButtonThem1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonThem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThem1ActionPerformed(evt);
            }
        });
        jPanelQLTaikhoan.add(jButtonThem1);
        jButtonThem1.setBounds(250, 363, 102, 40);

        jButtonSua1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonSua1.setForeground(new java.awt.Color(0, 0, 204));
        jButtonSua1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconsua.png"))); // NOI18N
        jButtonSua1.setText("Sửa");
        jButtonSua1.setBorder(null);
        jButtonSua1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelQLTaikhoan.add(jButtonSua1);
        jButtonSua1.setBounds(360, 363, 88, 40);

        jButtonXoa1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonXoa1.setForeground(new java.awt.Color(0, 0, 204));
        jButtonXoa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconxoa.png"))); // NOI18N
        jButtonXoa1.setText("Xóa");
        jButtonXoa1.setBorder(null);
        jButtonXoa1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelQLTaikhoan.add(jButtonXoa1);
        jButtonXoa1.setBounds(460, 363, 91, 40);

        jButtonLuu1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonLuu1.setForeground(new java.awt.Color(0, 0, 204));
        jButtonLuu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconsave.png"))); // NOI18N
        jButtonLuu1.setText("Lưu");
        jButtonLuu1.setBorder(null);
        jButtonLuu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelQLTaikhoan.add(jButtonLuu1);
        jButtonLuu1.setBounds(560, 363, 88, 40);

        jButtonTrangchu1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonTrangchu1.setForeground(new java.awt.Color(0, 0, 204));
        jButtonTrangchu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconmenu.png"))); // NOI18N
        jButtonTrangchu1.setText("Trang chủ");
        jButtonTrangchu1.setBorder(null);
        jButtonTrangchu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelQLTaikhoan.add(jButtonTrangchu1);
        jButtonTrangchu1.setBounds(660, 363, 139, 40);

        jPanelInforTaikhoan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelInforTaikhoan.setLayout(null);

        jLabelTenNV.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelTenNV.setForeground(new java.awt.Color(0, 0, 204));
        jLabelTenNV.setText("Tên nhân viên:");
        jPanelInforTaikhoan.add(jLabelTenNV);
        jLabelTenNV.setBounds(11, 103, 100, 22);

        jTextFieldMaNV.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldMaNV.setForeground(new java.awt.Color(0, 0, 204));
        jTextFieldMaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMaNVActionPerformed(evt);
            }
        });
        jPanelInforTaikhoan.add(jTextFieldMaNV);
        jTextFieldMaNV.setBounds(115, 74, 107, 23);

        jTextFieldTenNV.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldTenNV.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforTaikhoan.add(jTextFieldTenNV);
        jTextFieldTenNV.setBounds(115, 103, 197, 23);

        jLabelMaquyen1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelMaquyen1.setForeground(new java.awt.Color(0, 0, 204));
        jLabelMaquyen1.setText("Mã quyền");
        jPanelInforTaikhoan.add(jLabelMaquyen1);
        jLabelMaquyen1.setBounds(11, 134, 68, 22);

        jLabelMatkhau.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelMatkhau.setForeground(new java.awt.Color(0, 0, 204));
        jLabelMatkhau.setText("Mật khẩu:");
        jPanelInforTaikhoan.add(jLabelMatkhau);
        jLabelMatkhau.setBounds(11, 164, 68, 22);

        jTextFieldEmail.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldEmail.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforTaikhoan.add(jTextFieldEmail);
        jTextFieldEmail.setBounds(115, 192, 130, 23);

        jTextFieldMatkhau.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldMatkhau.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforTaikhoan.add(jTextFieldMatkhau);
        jTextFieldMatkhau.setBounds(115, 163, 123, 23);

        jLabelEmail.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelEmail.setForeground(new java.awt.Color(0, 0, 204));
        jLabelEmail.setText("Email:");
        jPanelInforTaikhoan.add(jLabelEmail);
        jLabelEmail.setBounds(11, 192, 44, 22);

        jLabelTimkiem1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelTimkiem1.setForeground(new java.awt.Color(0, 0, 204));
        jLabelTimkiem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconsearch.png"))); // NOI18N
        jLabelTimkiem1.setText("Tìm kiếm:");
        jPanelInforTaikhoan.add(jLabelTimkiem1);
        jLabelTimkiem1.setBounds(11, 12, 100, 31);

        jTextFieldTimkiem1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldTimkiem1.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforTaikhoan.add(jTextFieldTimkiem1);
        jTextFieldTimkiem1.setBounds(115, 12, 126, 31);

        jComboBoxMaquyen.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jComboBoxMaquyen.setForeground(new java.awt.Color(0, 0, 204));
        jComboBoxMaquyen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanelInforTaikhoan.add(jComboBoxMaquyen);
        jComboBoxMaquyen.setBounds(115, 134, 99, 23);

        jLabelMaNV.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelMaNV.setForeground(new java.awt.Color(0, 0, 204));
        jLabelMaNV.setText("Mã nhân viên:");
        jPanelInforTaikhoan.add(jLabelMaNV);
        jLabelMaNV.setBounds(11, 74, 100, 22);

        jTableQLTaikhoan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTableQLTaikhoan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTableQLTaikhoan.setForeground(new java.awt.Color(0, 0, 204));
        jTableQLTaikhoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneBangTaikhoan.setViewportView(jTableQLTaikhoan);

        jPanelInforTaikhoan.add(jScrollPaneBangTaikhoan);
        jScrollPaneBangTaikhoan.setBounds(340, 0, 340, 290);

        jPanelQLTaikhoan.add(jPanelInforTaikhoan);
        jPanelInforTaikhoan.setBounds(70, 60, 680, 290);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/image17.png"))); // NOI18N
        jPanelQLTaikhoan.add(jLabel1);
        jLabel1.setBounds(0, 0, 820, 410);

        jTabbedPaneQLTaikhoan.addTab("QL Tài khoản", jPanelQLTaikhoan);

        jPanelQLQuyentruycap.setLayout(null);

        jLabelQLQuyentruycap.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabelQLQuyentruycap.setForeground(new java.awt.Color(255, 0, 0));
        jLabelQLQuyentruycap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelQLQuyentruycap.setText("Quản lý Quyền truy cập");
        jPanelQLQuyentruycap.add(jLabelQLQuyentruycap);
        jLabelQLQuyentruycap.setBounds(220, 20, 400, 40);

        jButtonBack2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonBack2.setForeground(new java.awt.Color(0, 0, 204));
        jButtonBack2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconback.png"))); // NOI18N
        jButtonBack2.setText("Back");
        jPanelQLQuyentruycap.add(jButtonBack2);
        jButtonBack2.setBounds(10, 363, 107, 40);

        jButtonNext2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonNext2.setForeground(new java.awt.Color(0, 0, 204));
        jButtonNext2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconnext.png"))); // NOI18N
        jButtonNext2.setText("Next");
        jPanelQLQuyentruycap.add(jButtonNext2);
        jButtonNext2.setBounds(130, 363, 105, 40);

        jButtonThem2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonThem2.setForeground(new java.awt.Color(0, 0, 204));
        jButtonThem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconadd.png"))); // NOI18N
        jButtonThem2.setText("Thêm");
        jButtonThem2.setBorder(null);
        jButtonThem2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonThem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThem2ActionPerformed(evt);
            }
        });
        jPanelQLQuyentruycap.add(jButtonThem2);
        jButtonThem2.setBounds(240, 363, 102, 40);

        jButtonSua2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonSua2.setForeground(new java.awt.Color(0, 0, 204));
        jButtonSua2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconsua.png"))); // NOI18N
        jButtonSua2.setText("Sửa");
        jButtonSua2.setBorder(null);
        jButtonSua2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelQLQuyentruycap.add(jButtonSua2);
        jButtonSua2.setBounds(360, 363, 88, 40);

        jButtonXoa2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonXoa2.setForeground(new java.awt.Color(0, 0, 204));
        jButtonXoa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconxoa.png"))); // NOI18N
        jButtonXoa2.setText("Xóa");
        jButtonXoa2.setBorder(null);
        jButtonXoa2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelQLQuyentruycap.add(jButtonXoa2);
        jButtonXoa2.setBounds(460, 363, 91, 40);

        jButtonLuu2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonLuu2.setForeground(new java.awt.Color(0, 0, 204));
        jButtonLuu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconsave.png"))); // NOI18N
        jButtonLuu2.setText("Lưu");
        jButtonLuu2.setBorder(null);
        jButtonLuu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelQLQuyentruycap.add(jButtonLuu2);
        jButtonLuu2.setBounds(560, 363, 88, 40);

        jButtonTrangchu2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonTrangchu2.setForeground(new java.awt.Color(0, 0, 204));
        jButtonTrangchu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconmenu.png"))); // NOI18N
        jButtonTrangchu2.setText("Trang chủ");
        jButtonTrangchu2.setBorder(null);
        jButtonTrangchu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelQLQuyentruycap.add(jButtonTrangchu2);
        jButtonTrangchu2.setBounds(660, 363, 139, 40);

        jPanelInforQuyentruycap.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelInforQuyentruycap.setLayout(null);

        jLabelChucvu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelChucvu.setForeground(new java.awt.Color(0, 0, 204));
        jLabelChucvu.setText("Chức vụ");
        jPanelInforQuyentruycap.add(jLabelChucvu);
        jLabelChucvu.setBounds(11, 78, 100, 22);

        jTextFieldMaquyen.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldMaquyen.setForeground(new java.awt.Color(0, 0, 204));
        jTextFieldMaquyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMaquyenActionPerformed(evt);
            }
        });
        jPanelInforQuyentruycap.add(jTextFieldMaquyen);
        jTextFieldMaquyen.setBounds(115, 49, 126, 23);

        jTextFieldChucvu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldChucvu.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforQuyentruycap.add(jTextFieldChucvu);
        jTextFieldChucvu.setBounds(115, 78, 107, 23);

        jLabelTimkiem2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelTimkiem2.setForeground(new java.awt.Color(0, 0, 204));
        jLabelTimkiem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconsearch.png"))); // NOI18N
        jLabelTimkiem2.setText("Tìm kiếm:");
        jPanelInforQuyentruycap.add(jLabelTimkiem2);
        jLabelTimkiem2.setBounds(11, 12, 100, 31);

        jTextFieldTimkiem2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldTimkiem2.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforQuyentruycap.add(jTextFieldTimkiem2);
        jTextFieldTimkiem2.setBounds(115, 12, 126, 31);

        jLabelMaquyen2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelMaquyen2.setForeground(new java.awt.Color(0, 0, 204));
        jLabelMaquyen2.setText("Mã quyền:");
        jPanelInforQuyentruycap.add(jLabelMaquyen2);
        jLabelMaquyen2.setBounds(11, 49, 100, 22);

        jLabelQuyen.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelQuyen.setForeground(new java.awt.Color(0, 0, 204));
        jLabelQuyen.setText("Quyền:");
        jPanelInforQuyentruycap.add(jLabelQuyen);
        jLabelQuyen.setBounds(11, 107, 90, 22);

        jCheckBoxBanve.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCheckBoxBanve.setForeground(new java.awt.Color(0, 0, 204));
        jCheckBoxBanve.setText("Bán vé");
        jPanelInforQuyentruycap.add(jCheckBoxBanve);
        jCheckBoxBanve.setBounds(11, 136, 63, 25);

        jCheckBoxQLKH.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCheckBoxQLKH.setForeground(new java.awt.Color(0, 0, 204));
        jCheckBoxQLKH.setText("QL Khách hàng");
        jPanelInforQuyentruycap.add(jCheckBoxQLKH);
        jCheckBoxQLKH.setBounds(11, 164, 115, 25);

        jCheckBoxDoimatkhau.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCheckBoxDoimatkhau.setForeground(new java.awt.Color(0, 0, 204));
        jCheckBoxDoimatkhau.setText("Đổi mật khẩu");
        jPanelInforQuyentruycap.add(jCheckBoxDoimatkhau);
        jCheckBoxDoimatkhau.setBounds(126, 136, 117, 25);

        jCheckBoxQLTK.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCheckBoxQLTK.setForeground(new java.awt.Color(0, 0, 204));
        jCheckBoxQLTK.setText("QL Tài khoản");
        jPanelInforQuyentruycap.add(jCheckBoxQLTK);
        jCheckBoxQLTK.setBounds(11, 192, 115, 25);

        jCheckBoxTracuu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCheckBoxTracuu.setForeground(new java.awt.Color(0, 0, 204));
        jCheckBoxTracuu.setText("Tra cứu mã vé");
        jPanelInforQuyentruycap.add(jCheckBoxTracuu);
        jCheckBoxTracuu.setBounds(253, 136, 109, 25);

        jCheckBoxQLPhim.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCheckBoxQLPhim.setForeground(new java.awt.Color(0, 0, 204));
        jCheckBoxQLPhim.setText("QL Phim");
        jPanelInforQuyentruycap.add(jCheckBoxQLPhim);
        jCheckBoxQLPhim.setBounds(11, 220, 115, 25);

        jCheckBoxQLPhongchieu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCheckBoxQLPhongchieu.setForeground(new java.awt.Color(0, 0, 204));
        jCheckBoxQLPhongchieu.setText("QL Phòng chiếu");
        jPanelInforQuyentruycap.add(jCheckBoxQLPhongchieu);
        jCheckBoxQLPhongchieu.setBounds(126, 164, 117, 25);

        jCheckBoxQLLichchieu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCheckBoxQLLichchieu.setForeground(new java.awt.Color(0, 0, 204));
        jCheckBoxQLLichchieu.setText("QL Lịch chiếu");
        jPanelInforQuyentruycap.add(jCheckBoxQLLichchieu);
        jCheckBoxQLLichchieu.setBounds(126, 192, 117, 25);

        jCheckBoxQLKhuyenmai.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCheckBoxQLKhuyenmai.setForeground(new java.awt.Color(0, 0, 204));
        jCheckBoxQLKhuyenmai.setText("QL Khuyến mãi");
        jPanelInforQuyentruycap.add(jCheckBoxQLKhuyenmai);
        jCheckBoxQLKhuyenmai.setBounds(126, 220, 117, 25);

        jCheckBoxQLGiave.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCheckBoxQLGiave.setForeground(new java.awt.Color(0, 0, 204));
        jCheckBoxQLGiave.setText("QL Giá vé");
        jPanelInforQuyentruycap.add(jCheckBoxQLGiave);
        jCheckBoxQLGiave.setBounds(253, 164, 83, 25);

        jCheckBoxThongke.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCheckBoxThongke.setForeground(new java.awt.Color(0, 0, 204));
        jCheckBoxThongke.setText("Thống kê");
        jPanelInforQuyentruycap.add(jCheckBoxThongke);
        jCheckBoxThongke.setBounds(253, 192, 101, 25);

        jTableQLQuyentruycap.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTableQLQuyentruycap.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTableQLQuyentruycap.setForeground(new java.awt.Color(0, 0, 204));
        jTableQLQuyentruycap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneBangQuyentruycap.setViewportView(jTableQLQuyentruycap);

        jPanelInforQuyentruycap.add(jScrollPaneBangQuyentruycap);
        jScrollPaneBangQuyentruycap.setBounds(370, 0, 320, 270);

        jPanelQLQuyentruycap.add(jPanelInforQuyentruycap);
        jPanelInforQuyentruycap.setBounds(60, 80, 690, 270);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/image23.gif"))); // NOI18N
        jPanelQLQuyentruycap.add(jLabel2);
        jLabel2.setBounds(0, 0, 820, 410);

        jTabbedPaneQLTaikhoan.addTab("QL Quyền truy cập", jPanelQLQuyentruycap);

        getContentPane().add(jTabbedPaneQLTaikhoan);
        jTabbedPaneQLTaikhoan.setBounds(0, 40, 820, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_jLabelMinimizeMouseClicked

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jButtonThem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThem1ActionPerformed

    }//GEN-LAST:event_jButtonThem1ActionPerformed

    private void jButtonThem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThem2ActionPerformed

    }//GEN-LAST:event_jButtonThem2ActionPerformed

    private void jTextFieldMaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMaNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMaNVActionPerformed

    private void jTextFieldMaquyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMaquyenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMaquyenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormQLTaikhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormQLTaikhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormQLTaikhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormQLTaikhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormQLTaikhoan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack1;
    private javax.swing.JButton jButtonBack2;
    private javax.swing.JButton jButtonLuu1;
    private javax.swing.JButton jButtonLuu2;
    private javax.swing.JButton jButtonNext1;
    private javax.swing.JButton jButtonNext2;
    private javax.swing.JButton jButtonSua1;
    private javax.swing.JButton jButtonSua2;
    private javax.swing.JButton jButtonThem1;
    private javax.swing.JButton jButtonThem2;
    private javax.swing.JButton jButtonTrangchu1;
    private javax.swing.JButton jButtonTrangchu2;
    private javax.swing.JButton jButtonXoa1;
    private javax.swing.JButton jButtonXoa2;
    private javax.swing.JCheckBox jCheckBoxBanve;
    private javax.swing.JCheckBox jCheckBoxDoimatkhau;
    private javax.swing.JCheckBox jCheckBoxQLGiave;
    private javax.swing.JCheckBox jCheckBoxQLKH;
    private javax.swing.JCheckBox jCheckBoxQLKhuyenmai;
    private javax.swing.JCheckBox jCheckBoxQLLichchieu;
    private javax.swing.JCheckBox jCheckBoxQLPhim;
    private javax.swing.JCheckBox jCheckBoxQLPhongchieu;
    private javax.swing.JCheckBox jCheckBoxQLTK;
    private javax.swing.JCheckBox jCheckBoxThongke;
    private javax.swing.JCheckBox jCheckBoxTracuu;
    private javax.swing.JComboBox<String> jComboBoxMaquyen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelChucvu;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelHeader;
    private javax.swing.JLabel jLabelMaNV;
    private javax.swing.JLabel jLabelMaquyen1;
    private javax.swing.JLabel jLabelMaquyen2;
    private javax.swing.JLabel jLabelMatkhau;
    private javax.swing.JLabel jLabelMinimize;
    private javax.swing.JLabel jLabelQLQuyentruycap;
    private javax.swing.JLabel jLabelQLTaikhoan;
    private javax.swing.JLabel jLabelQuyen;
    private javax.swing.JLabel jLabelTenNV;
    private javax.swing.JLabel jLabelTimkiem1;
    private javax.swing.JLabel jLabelTimkiem2;
    private javax.swing.JPanel jPanelInforQuyentruycap;
    private javax.swing.JPanel jPanelInforTaikhoan;
    private javax.swing.JPanel jPanelQLQuyentruycap;
    private javax.swing.JPanel jPanelQLTaikhoan;
    private javax.swing.JScrollPane jScrollPaneBangQuyentruycap;
    private javax.swing.JScrollPane jScrollPaneBangTaikhoan;
    private javax.swing.JTabbedPane jTabbedPaneQLTaikhoan;
    private javax.swing.JTable jTableQLQuyentruycap;
    private javax.swing.JTable jTableQLTaikhoan;
    private javax.swing.JTextField jTextFieldChucvu;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldMaNV;
    private javax.swing.JTextField jTextFieldMaquyen;
    private javax.swing.JTextField jTextFieldMatkhau;
    private javax.swing.JTextField jTextFieldTenNV;
    private javax.swing.JTextField jTextFieldTimkiem1;
    private javax.swing.JTextField jTextFieldTimkiem2;
    // End of variables declaration//GEN-END:variables
}
