/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author ~Midori Mato~
 */
public class FormQLPhongchieu extends javax.swing.JFrame {

  
    public FormQLPhongchieu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMinimize = new javax.swing.JLabel();
        jLabelHeader = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jTabbedPhongchieu = new javax.swing.JTabbedPane();
        jPanelQLPhongchieu = new javax.swing.JPanel();
        jLabelQLPhongchieu = new javax.swing.JLabel();
        jButtonBack1 = new javax.swing.JButton();
        jButtonNext1 = new javax.swing.JButton();
        jButtonThem1 = new javax.swing.JButton();
        jButtonSua1 = new javax.swing.JButton();
        jButtonXoa1 = new javax.swing.JButton();
        jButtonLuu1 = new javax.swing.JButton();
        jButtonTrangchu1 = new javax.swing.JButton();
        jPanelInforKH = new javax.swing.JPanel();
        jLabelMadinhdang = new javax.swing.JLabel();
        jTextFieldMaphong1 = new javax.swing.JTextField();
        jTextFieldTen1 = new javax.swing.JTextField();
        jLabelNgaysinh = new javax.swing.JLabel();
        jLabelGioitinh = new javax.swing.JLabel();
        jTextFieldSodienthoai = new javax.swing.JTextField();
        jTextFieldSoCMND = new javax.swing.JTextField();
        jLabelTimkiem1 = new javax.swing.JLabel();
        jTextFieldTimkiem1 = new javax.swing.JTextField();
        jLabelMaphong1 = new javax.swing.JLabel();
        jScrollPaneBangKH = new javax.swing.JScrollPane();
        jTableQLKH = new javax.swing.JTable();
        jLabelBackground = new javax.swing.JLabel();
        jPanelQLGhe = new javax.swing.JPanel();
        jLabelQLPhongchieu1 = new javax.swing.JLabel();
        jButtonBack2 = new javax.swing.JButton();
        jButtonNext2 = new javax.swing.JButton();
        jButtonThem2 = new javax.swing.JButton();
        jButtonSua2 = new javax.swing.JButton();
        jButtonXoa2 = new javax.swing.JButton();
        jButtonLuu2 = new javax.swing.JButton();
        jButtonTrangchu2 = new javax.swing.JButton();
        jPanelInforGhe = new javax.swing.JPanel();
        jLabelMaghe = new javax.swing.JLabel();
        jTextFieldMaphong = new javax.swing.JTextField();
        jLabelLoaighe = new javax.swing.JLabel();
        jLabelHang = new javax.swing.JLabel();
        jTextFieldHang = new javax.swing.JTextField();
        jTextFieldSothutu = new javax.swing.JTextField();
        jLabelTimkiem2 = new javax.swing.JLabel();
        jTextFieldTimkiem2 = new javax.swing.JTextField();
        jLabelMaphong2 = new javax.swing.JLabel();
        jLabelSothutu = new javax.swing.JLabel();
        jComboBoxLoaighe = new javax.swing.JComboBox<>();
        jTextFieldMaghe2 = new javax.swing.JTextField();
        jScrollPaneBangghe = new javax.swing.JScrollPane();
        jTableQLGhe = new javax.swing.JTable();
        jLabelBackground2 = new javax.swing.JLabel();
        jPanelQLLoaighe = new javax.swing.JPanel();
        jLabelQLLoaighe = new javax.swing.JLabel();
        jButtonBack3 = new javax.swing.JButton();
        jButtonNext3 = new javax.swing.JButton();
        jButtonThem3 = new javax.swing.JButton();
        jButtonSua3 = new javax.swing.JButton();
        jButtonXoa3 = new javax.swing.JButton();
        jButtonLuu3 = new javax.swing.JButton();
        jButtonTrangchu3 = new javax.swing.JButton();
        jPanelInforKH1 = new javax.swing.JPanel();
        jLabelMadinhdang1 = new javax.swing.JLabel();
        jTextFieldLoaighe = new javax.swing.JTextField();
        jTextFieldPhuthughe = new javax.swing.JTextField();
        jLabelTimkiem3 = new javax.swing.JLabel();
        jTextFieldTimkiem3 = new javax.swing.JTextField();
        jLabelMaphong3 = new javax.swing.JLabel();
        jScrollPaneBangLoaighe = new javax.swing.JScrollPane();
        jTableQLLoaighe = new javax.swing.JTable();
        jLabelBackground3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(820, 478));
        setResizable(false);
        setSize(new java.awt.Dimension(820, 478));
        getContentPane().setLayout(null);

        jLabelMinimize.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelMinimize);
        jLabelMinimize.setBounds(710, 0, 50, 40);

        jLabelHeader.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelHeader.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/image0.png"))); // NOI18N
        getContentPane().add(jLabelHeader);
        jLabelHeader.setBounds(0, 0, 820, 40);

        jLabelClose.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelClose);
        jLabelClose.setBounds(770, 0, 50, 40);

        jTabbedPhongchieu.setForeground(new java.awt.Color(0, 0, 204));
        jTabbedPhongchieu.setMinimumSize(new java.awt.Dimension(138, 60));
        jTabbedPhongchieu.setPreferredSize(new java.awt.Dimension(138, 60));

        jPanelQLPhongchieu.setLayout(null);

        jLabelQLPhongchieu.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabelQLPhongchieu.setForeground(new java.awt.Color(255, 0, 0));
        jLabelQLPhongchieu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelQLPhongchieu.setText("Quản lý Phòng chiếu");
        jPanelQLPhongchieu.add(jLabelQLPhongchieu);
        jLabelQLPhongchieu.setBounds(250, 10, 340, 40);

        jButtonBack1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonBack1.setForeground(new java.awt.Color(0, 0, 204));
        jButtonBack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconback.png"))); // NOI18N
        jButtonBack1.setText("Back");
        jPanelQLPhongchieu.add(jButtonBack1);
        jButtonBack1.setBounds(10, 353, 107, 40);

        jButtonNext1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonNext1.setForeground(new java.awt.Color(0, 0, 204));
        jButtonNext1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconnext.png"))); // NOI18N
        jButtonNext1.setText("Next");
        jPanelQLPhongchieu.add(jButtonNext1);
        jButtonNext1.setBounds(127, 353, 105, 40);

        jButtonThem1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonThem1.setForeground(new java.awt.Color(0, 0, 204));
        jButtonThem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconadd.png"))); // NOI18N
        jButtonThem1.setText("Thêm");
        jButtonThem1.setBorder(null);
        jButtonThem1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonThem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThem1ActionPerformed(evt);
            }
        });
        jPanelQLPhongchieu.add(jButtonThem1);
        jButtonThem1.setBounds(242, 353, 102, 40);

        jButtonSua1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonSua1.setForeground(new java.awt.Color(0, 0, 204));
        jButtonSua1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconsua.png"))); // NOI18N
        jButtonSua1.setText("Sửa");
        jButtonSua1.setBorder(null);
        jButtonSua1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelQLPhongchieu.add(jButtonSua1);
        jButtonSua1.setBounds(354, 353, 88, 40);

        jButtonXoa1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonXoa1.setForeground(new java.awt.Color(0, 0, 204));
        jButtonXoa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconxoa.png"))); // NOI18N
        jButtonXoa1.setText("Xóa");
        jButtonXoa1.setBorder(null);
        jButtonXoa1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelQLPhongchieu.add(jButtonXoa1);
        jButtonXoa1.setBounds(458, 353, 91, 40);

        jButtonLuu1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonLuu1.setForeground(new java.awt.Color(0, 0, 204));
        jButtonLuu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconsave.png"))); // NOI18N
        jButtonLuu1.setText("Lưu");
        jButtonLuu1.setBorder(null);
        jButtonLuu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelQLPhongchieu.add(jButtonLuu1);
        jButtonLuu1.setBounds(559, 353, 88, 40);

        jButtonTrangchu1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonTrangchu1.setForeground(new java.awt.Color(0, 0, 204));
        jButtonTrangchu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconmenu.png"))); // NOI18N
        jButtonTrangchu1.setText("Trang chủ");
        jButtonTrangchu1.setBorder(null);
        jButtonTrangchu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelQLPhongchieu.add(jButtonTrangchu1);
        jButtonTrangchu1.setBounds(657, 353, 139, 40);

        jPanelInforKH.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelInforKH.setLayout(null);

        jLabelMadinhdang.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelMadinhdang.setForeground(new java.awt.Color(0, 0, 204));
        jLabelMadinhdang.setText("Mã định dạng:");
        jPanelInforKH.add(jLabelMadinhdang);
        jLabelMadinhdang.setBounds(11, 115, 88, 22);

        jTextFieldMaphong1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldMaphong1.setForeground(new java.awt.Color(0, 0, 204));
        jTextFieldMaphong1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMaphong1ActionPerformed(evt);
            }
        });
        jPanelInforKH.add(jTextFieldMaphong1);
        jTextFieldMaphong1.setBounds(103, 86, 123, 23);

        jTextFieldTen1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldTen1.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforKH.add(jTextFieldTen1);
        jTextFieldTen1.setBounds(103, 115, 123, 23);

        jLabelNgaysinh.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelNgaysinh.setForeground(new java.awt.Color(0, 0, 204));
        jLabelNgaysinh.setText("Tên phòng:");
        jPanelInforKH.add(jLabelNgaysinh);
        jLabelNgaysinh.setBounds(11, 144, 68, 22);

        jLabelGioitinh.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelGioitinh.setForeground(new java.awt.Color(0, 0, 204));
        jLabelGioitinh.setText("Số lượng ghế:");
        jPanelInforKH.add(jLabelGioitinh);
        jLabelGioitinh.setBounds(11, 173, 88, 22);

        jTextFieldSodienthoai.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldSodienthoai.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforKH.add(jTextFieldSodienthoai);
        jTextFieldSodienthoai.setBounds(103, 144, 123, 23);

        jTextFieldSoCMND.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldSoCMND.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforKH.add(jTextFieldSoCMND);
        jTextFieldSoCMND.setBounds(103, 173, 123, 23);

        jLabelTimkiem1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelTimkiem1.setForeground(new java.awt.Color(0, 0, 204));
        jLabelTimkiem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconsearch.png"))); // NOI18N
        jLabelTimkiem1.setText("Tìm kiếm:");
        jPanelInforKH.add(jLabelTimkiem1);
        jLabelTimkiem1.setBounds(11, 12, 100, 31);

        jTextFieldTimkiem1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldTimkiem1.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforKH.add(jTextFieldTimkiem1);
        jTextFieldTimkiem1.setBounds(115, 12, 126, 31);

        jLabelMaphong1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelMaphong1.setForeground(new java.awt.Color(0, 0, 204));
        jLabelMaphong1.setText("Mã phòng:");
        jPanelInforKH.add(jLabelMaphong1);
        jLabelMaphong1.setBounds(11, 86, 86, 22);

        jTableQLKH.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTableQLKH.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTableQLKH.setForeground(new java.awt.Color(0, 0, 204));
        jTableQLKH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneBangKH.setViewportView(jTableQLKH);

        jPanelInforKH.add(jScrollPaneBangKH);
        jScrollPaneBangKH.setBounds(300, 0, 290, 270);

        jPanelQLPhongchieu.add(jPanelInforKH);
        jPanelInforKH.setBounds(110, 70, 590, 270);

        jLabelBackground.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/image1.jpg"))); // NOI18N
        jLabelBackground.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jLabelBackground.setMinimumSize(new java.awt.Dimension(1920, 1080));
        jLabelBackground.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanelQLPhongchieu.add(jLabelBackground);
        jLabelBackground.setBounds(0, 0, 820, 410);

        jTabbedPhongchieu.addTab("QL Phòng chiếu", jPanelQLPhongchieu);

        jPanelQLGhe.setLayout(null);

        jLabelQLPhongchieu1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabelQLPhongchieu1.setForeground(new java.awt.Color(255, 0, 0));
        jLabelQLPhongchieu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelQLPhongchieu1.setText("Quản lý Ghế");
        jPanelQLGhe.add(jLabelQLPhongchieu1);
        jLabelQLPhongchieu1.setBounds(270, 10, 250, 40);

        jButtonBack2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonBack2.setForeground(new java.awt.Color(0, 0, 204));
        jButtonBack2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconback.png"))); // NOI18N
        jButtonBack2.setText("Back");
        jPanelQLGhe.add(jButtonBack2);
        jButtonBack2.setBounds(10, 353, 107, 40);

        jButtonNext2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonNext2.setForeground(new java.awt.Color(0, 0, 204));
        jButtonNext2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconnext.png"))); // NOI18N
        jButtonNext2.setText("Next");
        jPanelQLGhe.add(jButtonNext2);
        jButtonNext2.setBounds(127, 353, 105, 40);

        jButtonThem2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonThem2.setForeground(new java.awt.Color(0, 0, 204));
        jButtonThem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconadd.png"))); // NOI18N
        jButtonThem2.setText("Thêm");
        jButtonThem2.setBorder(null);
        jButtonThem2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonThem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThem2ActionPerformed(evt);
            }
        });
        jPanelQLGhe.add(jButtonThem2);
        jButtonThem2.setBounds(242, 353, 102, 40);

        jButtonSua2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonSua2.setForeground(new java.awt.Color(0, 0, 204));
        jButtonSua2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconsua.png"))); // NOI18N
        jButtonSua2.setText("Sửa");
        jButtonSua2.setBorder(null);
        jButtonSua2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelQLGhe.add(jButtonSua2);
        jButtonSua2.setBounds(354, 353, 88, 40);

        jButtonXoa2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonXoa2.setForeground(new java.awt.Color(0, 0, 204));
        jButtonXoa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconxoa.png"))); // NOI18N
        jButtonXoa2.setText("Xóa");
        jButtonXoa2.setBorder(null);
        jButtonXoa2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelQLGhe.add(jButtonXoa2);
        jButtonXoa2.setBounds(458, 353, 91, 40);

        jButtonLuu2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonLuu2.setForeground(new java.awt.Color(0, 0, 204));
        jButtonLuu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconsave.png"))); // NOI18N
        jButtonLuu2.setText("Lưu");
        jButtonLuu2.setBorder(null);
        jButtonLuu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelQLGhe.add(jButtonLuu2);
        jButtonLuu2.setBounds(559, 353, 88, 40);

        jButtonTrangchu2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonTrangchu2.setForeground(new java.awt.Color(0, 0, 204));
        jButtonTrangchu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconmenu.png"))); // NOI18N
        jButtonTrangchu2.setText("Trang chủ");
        jButtonTrangchu2.setBorder(null);
        jButtonTrangchu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelQLGhe.add(jButtonTrangchu2);
        jButtonTrangchu2.setBounds(657, 353, 139, 40);

        jPanelInforGhe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelInforGhe.setLayout(null);

        jLabelMaghe.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelMaghe.setForeground(new java.awt.Color(0, 0, 204));
        jLabelMaghe.setText("Mã ghế:");
        jPanelInforGhe.add(jLabelMaghe);
        jLabelMaghe.setBounds(11, 62, 68, 22);

        jTextFieldMaphong.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldMaphong.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforGhe.add(jTextFieldMaphong);
        jTextFieldMaphong.setBounds(95, 120, 59, 23);

        jLabelLoaighe.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelLoaighe.setForeground(new java.awt.Color(0, 0, 204));
        jLabelLoaighe.setText("Loại ghế:");
        jPanelInforGhe.add(jLabelLoaighe);
        jLabelLoaighe.setBounds(11, 91, 68, 22);

        jLabelHang.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelHang.setForeground(new java.awt.Color(0, 0, 204));
        jLabelHang.setText("Hàng:");
        jPanelInforGhe.add(jLabelHang);
        jLabelHang.setBounds(11, 150, 66, 22);

        jTextFieldHang.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldHang.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforGhe.add(jTextFieldHang);
        jTextFieldHang.setBounds(95, 150, 59, 23);

        jTextFieldSothutu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldSothutu.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforGhe.add(jTextFieldSothutu);
        jTextFieldSothutu.setBounds(95, 179, 59, 23);

        jLabelTimkiem2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelTimkiem2.setForeground(new java.awt.Color(0, 0, 204));
        jLabelTimkiem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconsearch.png"))); // NOI18N
        jLabelTimkiem2.setText("Tìm kiếm:");
        jPanelInforGhe.add(jLabelTimkiem2);
        jLabelTimkiem2.setBounds(11, 12, 100, 31);

        jTextFieldTimkiem2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldTimkiem2.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforGhe.add(jTextFieldTimkiem2);
        jTextFieldTimkiem2.setBounds(115, 12, 126, 31);

        jLabelMaphong2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelMaphong2.setForeground(new java.awt.Color(0, 0, 204));
        jLabelMaphong2.setText("Mã phòng:");
        jPanelInforGhe.add(jLabelMaphong2);
        jLabelMaphong2.setBounds(11, 120, 66, 22);

        jLabelSothutu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelSothutu.setForeground(new java.awt.Color(0, 0, 204));
        jLabelSothutu.setText("Số thứ tự:");
        jPanelInforGhe.add(jLabelSothutu);
        jLabelSothutu.setBounds(11, 179, 57, 22);

        jComboBoxLoaighe.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jComboBoxLoaighe.setForeground(new java.awt.Color(0, 0, 204));
        jComboBoxLoaighe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanelInforGhe.add(jComboBoxLoaighe);
        jComboBoxLoaighe.setBounds(93, 91, 63, 23);

        jTextFieldMaghe2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldMaghe2.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforGhe.add(jTextFieldMaghe2);
        jTextFieldMaghe2.setBounds(97, 62, 59, 23);

        jTableQLGhe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTableQLGhe.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTableQLGhe.setForeground(new java.awt.Color(0, 0, 204));
        jTableQLGhe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneBangghe.setViewportView(jTableQLGhe);

        jPanelInforGhe.add(jScrollPaneBangghe);
        jScrollPaneBangghe.setBounds(290, 0, 290, 270);

        jPanelQLGhe.add(jPanelInforGhe);
        jPanelInforGhe.setBounds(90, 70, 580, 270);

        jLabelBackground2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBackground2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/image10.jpg"))); // NOI18N
        jLabelBackground2.setMaximumSize(new java.awt.Dimension(1280, 618));
        jLabelBackground2.setMinimumSize(new java.awt.Dimension(1280, 618));
        jLabelBackground2.setPreferredSize(new java.awt.Dimension(1280, 618));
        jPanelQLGhe.add(jLabelBackground2);
        jLabelBackground2.setBounds(0, 0, 820, 420);

        jTabbedPhongchieu.addTab("QL Ghế", jPanelQLGhe);

        jPanelQLLoaighe.setLayout(null);

        jLabelQLLoaighe.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabelQLLoaighe.setForeground(new java.awt.Color(255, 0, 0));
        jLabelQLLoaighe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelQLLoaighe.setText("Quản lý Loại ghế");
        jPanelQLLoaighe.add(jLabelQLLoaighe);
        jLabelQLLoaighe.setBounds(270, 10, 290, 40);

        jButtonBack3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonBack3.setForeground(new java.awt.Color(0, 0, 204));
        jButtonBack3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconback.png"))); // NOI18N
        jButtonBack3.setText("Back");
        jPanelQLLoaighe.add(jButtonBack3);
        jButtonBack3.setBounds(10, 350, 107, 40);

        jButtonNext3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonNext3.setForeground(new java.awt.Color(0, 0, 204));
        jButtonNext3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconnext.png"))); // NOI18N
        jButtonNext3.setText("Next");
        jPanelQLLoaighe.add(jButtonNext3);
        jButtonNext3.setBounds(130, 350, 105, 40);

        jButtonThem3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonThem3.setForeground(new java.awt.Color(0, 0, 204));
        jButtonThem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconadd.png"))); // NOI18N
        jButtonThem3.setText("Thêm");
        jButtonThem3.setBorder(null);
        jButtonThem3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonThem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThem3ActionPerformed(evt);
            }
        });
        jPanelQLLoaighe.add(jButtonThem3);
        jButtonThem3.setBounds(250, 350, 102, 40);

        jButtonSua3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonSua3.setForeground(new java.awt.Color(0, 0, 204));
        jButtonSua3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconsua.png"))); // NOI18N
        jButtonSua3.setText("Sửa");
        jButtonSua3.setBorder(null);
        jButtonSua3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelQLLoaighe.add(jButtonSua3);
        jButtonSua3.setBounds(360, 350, 88, 40);

        jButtonXoa3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonXoa3.setForeground(new java.awt.Color(0, 0, 204));
        jButtonXoa3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconxoa.png"))); // NOI18N
        jButtonXoa3.setText("Xóa");
        jButtonXoa3.setBorder(null);
        jButtonXoa3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelQLLoaighe.add(jButtonXoa3);
        jButtonXoa3.setBounds(460, 350, 91, 40);

        jButtonLuu3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonLuu3.setForeground(new java.awt.Color(0, 0, 204));
        jButtonLuu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconsave.png"))); // NOI18N
        jButtonLuu3.setText("Lưu");
        jButtonLuu3.setBorder(null);
        jButtonLuu3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelQLLoaighe.add(jButtonLuu3);
        jButtonLuu3.setBounds(560, 350, 88, 40);

        jButtonTrangchu3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonTrangchu3.setForeground(new java.awt.Color(0, 0, 204));
        jButtonTrangchu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconmenu.png"))); // NOI18N
        jButtonTrangchu3.setText("Trang chủ");
        jButtonTrangchu3.setBorder(null);
        jButtonTrangchu3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelQLLoaighe.add(jButtonTrangchu3);
        jButtonTrangchu3.setBounds(660, 350, 139, 40);

        jPanelInforKH1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelInforKH1.setLayout(null);

        jLabelMadinhdang1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelMadinhdang1.setForeground(new java.awt.Color(0, 0, 204));
        jLabelMadinhdang1.setText("Phụ thu ghế:");
        jPanelInforKH1.add(jLabelMadinhdang1);
        jLabelMadinhdang1.setBounds(11, 115, 88, 22);

        jTextFieldLoaighe.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldLoaighe.setForeground(new java.awt.Color(0, 0, 204));
        jTextFieldLoaighe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLoaigheActionPerformed(evt);
            }
        });
        jPanelInforKH1.add(jTextFieldLoaighe);
        jTextFieldLoaighe.setBounds(103, 86, 123, 23);

        jTextFieldPhuthughe.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldPhuthughe.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforKH1.add(jTextFieldPhuthughe);
        jTextFieldPhuthughe.setBounds(103, 115, 123, 23);

        jLabelTimkiem3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelTimkiem3.setForeground(new java.awt.Color(0, 0, 204));
        jLabelTimkiem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconsearch.png"))); // NOI18N
        jLabelTimkiem3.setText("Tìm kiếm:");
        jPanelInforKH1.add(jLabelTimkiem3);
        jLabelTimkiem3.setBounds(11, 12, 100, 31);

        jTextFieldTimkiem3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldTimkiem3.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforKH1.add(jTextFieldTimkiem3);
        jTextFieldTimkiem3.setBounds(115, 12, 126, 31);

        jLabelMaphong3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelMaphong3.setForeground(new java.awt.Color(0, 0, 204));
        jLabelMaphong3.setText("Loại ghế:");
        jPanelInforKH1.add(jLabelMaphong3);
        jLabelMaphong3.setBounds(11, 86, 86, 22);

        jTableQLLoaighe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTableQLLoaighe.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTableQLLoaighe.setForeground(new java.awt.Color(0, 0, 204));
        jTableQLLoaighe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneBangLoaighe.setViewportView(jTableQLLoaighe);

        jPanelInforKH1.add(jScrollPaneBangLoaighe);
        jScrollPaneBangLoaighe.setBounds(250, 0, 290, 270);

        jPanelQLLoaighe.add(jPanelInforKH1);
        jPanelInforKH1.setBounds(120, 70, 540, 270);

        jLabelBackground3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBackground3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/image14.jpg"))); // NOI18N
        jPanelQLLoaighe.add(jLabelBackground3);
        jLabelBackground3.setBounds(0, 0, 820, 430);

        jTabbedPhongchieu.addTab("QL Loại ghế", jPanelQLLoaighe);

        getContentPane().add(jTabbedPhongchieu);
        jTabbedPhongchieu.setBounds(0, 40, 820, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_jLabelMinimizeMouseClicked

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jButtonThem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThem1ActionPerformed

    }//GEN-LAST:event_jButtonThem1ActionPerformed

    private void jTextFieldMaphong1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMaphong1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMaphong1ActionPerformed

    private void jButtonThem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonThem2ActionPerformed

    private void jButtonThem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonThem3ActionPerformed

    private void jTextFieldLoaigheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLoaigheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLoaigheActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormQLPhongchieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormQLPhongchieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormQLPhongchieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormQLPhongchieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormQLPhongchieu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack1;
    private javax.swing.JButton jButtonBack2;
    private javax.swing.JButton jButtonBack3;
    private javax.swing.JButton jButtonLuu1;
    private javax.swing.JButton jButtonLuu2;
    private javax.swing.JButton jButtonLuu3;
    private javax.swing.JButton jButtonNext1;
    private javax.swing.JButton jButtonNext2;
    private javax.swing.JButton jButtonNext3;
    private javax.swing.JButton jButtonSua1;
    private javax.swing.JButton jButtonSua2;
    private javax.swing.JButton jButtonSua3;
    private javax.swing.JButton jButtonThem1;
    private javax.swing.JButton jButtonThem2;
    private javax.swing.JButton jButtonThem3;
    private javax.swing.JButton jButtonTrangchu1;
    private javax.swing.JButton jButtonTrangchu2;
    private javax.swing.JButton jButtonTrangchu3;
    private javax.swing.JButton jButtonXoa1;
    private javax.swing.JButton jButtonXoa2;
    private javax.swing.JButton jButtonXoa3;
    private javax.swing.JComboBox<String> jComboBoxLoaighe;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelBackground2;
    private javax.swing.JLabel jLabelBackground3;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelGioitinh;
    private javax.swing.JLabel jLabelHang;
    private javax.swing.JLabel jLabelHeader;
    private javax.swing.JLabel jLabelLoaighe;
    private javax.swing.JLabel jLabelMadinhdang;
    private javax.swing.JLabel jLabelMadinhdang1;
    private javax.swing.JLabel jLabelMaghe;
    private javax.swing.JLabel jLabelMaphong1;
    private javax.swing.JLabel jLabelMaphong2;
    private javax.swing.JLabel jLabelMaphong3;
    private javax.swing.JLabel jLabelMinimize;
    private javax.swing.JLabel jLabelNgaysinh;
    private javax.swing.JLabel jLabelQLLoaighe;
    private javax.swing.JLabel jLabelQLPhongchieu;
    private javax.swing.JLabel jLabelQLPhongchieu1;
    private javax.swing.JLabel jLabelSothutu;
    private javax.swing.JLabel jLabelTimkiem1;
    private javax.swing.JLabel jLabelTimkiem2;
    private javax.swing.JLabel jLabelTimkiem3;
    private javax.swing.JPanel jPanelInforGhe;
    private javax.swing.JPanel jPanelInforKH;
    private javax.swing.JPanel jPanelInforKH1;
    private javax.swing.JPanel jPanelQLGhe;
    private javax.swing.JPanel jPanelQLLoaighe;
    private javax.swing.JPanel jPanelQLPhongchieu;
    private javax.swing.JScrollPane jScrollPaneBangKH;
    private javax.swing.JScrollPane jScrollPaneBangLoaighe;
    private javax.swing.JScrollPane jScrollPaneBangghe;
    private javax.swing.JTabbedPane jTabbedPhongchieu;
    private javax.swing.JTable jTableQLGhe;
    private javax.swing.JTable jTableQLKH;
    private javax.swing.JTable jTableQLLoaighe;
    private javax.swing.JTextField jTextFieldHang;
    private javax.swing.JTextField jTextFieldLoaighe;
    private javax.swing.JTextField jTextFieldMaghe2;
    private javax.swing.JTextField jTextFieldMaphong;
    private javax.swing.JTextField jTextFieldMaphong1;
    private javax.swing.JTextField jTextFieldPhuthughe;
    private javax.swing.JTextField jTextFieldSoCMND;
    private javax.swing.JTextField jTextFieldSodienthoai;
    private javax.swing.JTextField jTextFieldSothutu;
    private javax.swing.JTextField jTextFieldTen1;
    private javax.swing.JTextField jTextFieldTimkiem1;
    private javax.swing.JTextField jTextFieldTimkiem2;
    private javax.swing.JTextField jTextFieldTimkiem3;
    // End of variables declaration//GEN-END:variables
}
