/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author ~Midori Mato~
 */
public class FormQLLichchieu extends javax.swing.JFrame {

    /**
     * Creates new form FormQLLichchieu
     */
    public FormQLLichchieu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelHeader = new javax.swing.JLabel();
        jLabelMinimize = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jLabelQLLichchieu = new javax.swing.JLabel();
        jButtonBack = new javax.swing.JButton();
        jButtonNext = new javax.swing.JButton();
        jButtonThem = new javax.swing.JButton();
        jButtonSua = new javax.swing.JButton();
        jButtonXoa = new javax.swing.JButton();
        jButtonLuu = new javax.swing.JButton();
        jButtonTrangchu = new javax.swing.JButton();
        jPanelInforKhuyenmai = new javax.swing.JPanel();
        jLabelMagia = new javax.swing.JLabel();
        jTextFieldMalichchieu = new javax.swing.JTextField();
        jLabelMaphong = new javax.swing.JLabel();
        jLabelMaphim = new javax.swing.JLabel();
        jLabelNgaychieu = new javax.swing.JLabel();
        jTextFieldMaphim = new javax.swing.JTextField();
        jDateChooserNgaychieu = new com.toedter.calendar.JDateChooser();
        jLabelTimkiem = new javax.swing.JLabel();
        jTextFieldTimkiem = new javax.swing.JTextField();
        jLabelMalichchieu = new javax.swing.JLabel();
        jLabelThoigianchieu = new javax.swing.JLabel();
        jTextFieldMagia = new javax.swing.JTextField();
        jTextFieldThoigianchieu = new javax.swing.JTextField();
        jTextFieldMaphong = new javax.swing.JTextField();
        jScrollPaneBangKhuyenmai = new javax.swing.JScrollPane();
        jTableQLKhuyenmai = new javax.swing.JTable();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(820, 478));
        setResizable(false);
        setSize(new java.awt.Dimension(820, 478));
        getContentPane().setLayout(null);

        jLabelHeader.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelHeader.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/image0.png"))); // NOI18N
        getContentPane().add(jLabelHeader);
        jLabelHeader.setBounds(0, 0, 820, 40);

        jLabelMinimize.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelMinimize);
        jLabelMinimize.setBounds(710, 0, 50, 40);

        jLabelClose.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelClose);
        jLabelClose.setBounds(770, 0, 50, 40);

        jLabelQLLichchieu.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabelQLLichchieu.setForeground(new java.awt.Color(255, 0, 0));
        jLabelQLLichchieu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelQLLichchieu.setText("Quản lý Lịch chiếu");
        getContentPane().add(jLabelQLLichchieu);
        jLabelQLLichchieu.setBounds(230, 50, 370, 50);

        jButtonBack.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonBack.setForeground(new java.awt.Color(0, 0, 204));
        jButtonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconback.png"))); // NOI18N
        jButtonBack.setText("Back");
        jButtonBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButtonBack);
        jButtonBack.setBounds(20, 413, 107, 40);

        jButtonNext.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonNext.setForeground(new java.awt.Color(0, 0, 204));
        jButtonNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconnext.png"))); // NOI18N
        jButtonNext.setText("Next");
        jButtonNext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButtonNext);
        jButtonNext.setBounds(140, 413, 105, 40);

        jButtonThem.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonThem.setForeground(new java.awt.Color(0, 0, 204));
        jButtonThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconadd.png"))); // NOI18N
        jButtonThem.setText("Thêm");
        jButtonThem.setBorder(null);
        jButtonThem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThemActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonThem);
        jButtonThem.setBounds(260, 413, 102, 40);

        jButtonSua.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonSua.setForeground(new java.awt.Color(0, 0, 204));
        jButtonSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconsua.png"))); // NOI18N
        jButtonSua.setText("Sửa");
        jButtonSua.setBorder(null);
        jButtonSua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButtonSua);
        jButtonSua.setBounds(370, 413, 88, 40);

        jButtonXoa.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonXoa.setForeground(new java.awt.Color(0, 0, 204));
        jButtonXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconxoa.png"))); // NOI18N
        jButtonXoa.setText("Xóa");
        jButtonXoa.setBorder(null);
        jButtonXoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButtonXoa);
        jButtonXoa.setBounds(470, 413, 91, 40);

        jButtonLuu.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonLuu.setForeground(new java.awt.Color(0, 0, 204));
        jButtonLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconsave.png"))); // NOI18N
        jButtonLuu.setText("Lưu");
        jButtonLuu.setBorder(null);
        jButtonLuu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButtonLuu);
        jButtonLuu.setBounds(570, 413, 88, 40);

        jButtonTrangchu.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonTrangchu.setForeground(new java.awt.Color(0, 0, 204));
        jButtonTrangchu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconmenu.png"))); // NOI18N
        jButtonTrangchu.setText("Trang chủ");
        jButtonTrangchu.setBorder(null);
        jButtonTrangchu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButtonTrangchu);
        jButtonTrangchu.setBounds(670, 413, 139, 40);

        jPanelInforKhuyenmai.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelInforKhuyenmai.setLayout(null);

        jLabelMagia.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelMagia.setForeground(new java.awt.Color(0, 0, 204));
        jLabelMagia.setText("Mã giá:");
        jPanelInforKhuyenmai.add(jLabelMagia);
        jLabelMagia.setBounds(11, 209, 41, 22);

        jTextFieldMalichchieu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldMalichchieu.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforKhuyenmai.add(jTextFieldMalichchieu);
        jTextFieldMalichchieu.setBounds(108, 61, 106, 23);

        jLabelMaphong.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelMaphong.setForeground(new java.awt.Color(0, 0, 204));
        jLabelMaphong.setText("Mã phòng:");
        jPanelInforKhuyenmai.add(jLabelMaphong);
        jLabelMaphong.setBounds(11, 180, 88, 22);

        jLabelMaphim.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelMaphim.setForeground(new java.awt.Color(0, 0, 204));
        jLabelMaphim.setText("Mã phim:");
        jPanelInforKhuyenmai.add(jLabelMaphim);
        jLabelMaphim.setBounds(11, 93, 80, 22);

        jLabelNgaychieu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelNgaychieu.setForeground(new java.awt.Color(0, 0, 204));
        jLabelNgaychieu.setText("Ngày chiếu:");
        jPanelInforKhuyenmai.add(jLabelNgaychieu);
        jLabelNgaychieu.setBounds(11, 122, 69, 22);

        jTextFieldMaphim.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldMaphim.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforKhuyenmai.add(jTextFieldMaphim);
        jTextFieldMaphim.setBounds(111, 93, 86, 23);

        jDateChooserNgaychieu.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforKhuyenmai.add(jDateChooserNgaychieu);
        jDateChooserNgaychieu.setBounds(111, 122, 124, 22);

        jLabelTimkiem.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelTimkiem.setForeground(new java.awt.Color(0, 0, 204));
        jLabelTimkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/iconsearch.png"))); // NOI18N
        jLabelTimkiem.setText("Tìm kiếm:");
        jPanelInforKhuyenmai.add(jLabelTimkiem);
        jLabelTimkiem.setBounds(11, 12, 100, 31);

        jTextFieldTimkiem.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldTimkiem.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforKhuyenmai.add(jTextFieldTimkiem);
        jTextFieldTimkiem.setBounds(115, 12, 126, 31);

        jLabelMalichchieu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelMalichchieu.setForeground(new java.awt.Color(0, 0, 204));
        jLabelMalichchieu.setText("Mã lịch chiếu:");
        jPanelInforKhuyenmai.add(jLabelMalichchieu);
        jLabelMalichchieu.setBounds(11, 61, 79, 22);

        jLabelThoigianchieu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelThoigianchieu.setForeground(new java.awt.Color(0, 0, 204));
        jLabelThoigianchieu.setText("Thời gian chiếu:");
        jPanelInforKhuyenmai.add(jLabelThoigianchieu);
        jLabelThoigianchieu.setBounds(11, 150, 96, 22);

        jTextFieldMagia.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldMagia.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforKhuyenmai.add(jTextFieldMagia);
        jTextFieldMagia.setBounds(111, 209, 89, 23);

        jTextFieldThoigianchieu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldThoigianchieu.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforKhuyenmai.add(jTextFieldThoigianchieu);
        jTextFieldThoigianchieu.setBounds(111, 150, 97, 23);

        jTextFieldMaphong.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldMaphong.setForeground(new java.awt.Color(0, 0, 204));
        jPanelInforKhuyenmai.add(jTextFieldMaphong);
        jTextFieldMaphong.setBounds(109, 180, 97, 23);

        jTableQLKhuyenmai.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTableQLKhuyenmai.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTableQLKhuyenmai.setForeground(new java.awt.Color(0, 0, 204));
        jTableQLKhuyenmai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneBangKhuyenmai.setViewportView(jTableQLKhuyenmai);

        jPanelInforKhuyenmai.add(jScrollPaneBangKhuyenmai);
        jScrollPaneBangKhuyenmai.setBounds(330, 0, 350, 290);

        getContentPane().add(jPanelInforKhuyenmai);
        jPanelInforKhuyenmai.setBounds(70, 110, 680, 290);

        jLabelBackground.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/image17.png"))); // NOI18N
        getContentPane().add(jLabelBackground);
        jLabelBackground.setBounds(0, 40, 820, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_jLabelMinimizeMouseClicked

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jButtonThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemActionPerformed

    }//GEN-LAST:event_jButtonThemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormQLLichchieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormQLLichchieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormQLLichchieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormQLLichchieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormQLLichchieu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonLuu;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonSua;
    private javax.swing.JButton jButtonThem;
    private javax.swing.JButton jButtonTrangchu;
    private javax.swing.JButton jButtonXoa;
    private com.toedter.calendar.JDateChooser jDateChooserNgaychieu;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelHeader;
    private javax.swing.JLabel jLabelMagia;
    private javax.swing.JLabel jLabelMalichchieu;
    private javax.swing.JLabel jLabelMaphim;
    private javax.swing.JLabel jLabelMaphong;
    private javax.swing.JLabel jLabelMinimize;
    private javax.swing.JLabel jLabelNgaychieu;
    private javax.swing.JLabel jLabelQLLichchieu;
    private javax.swing.JLabel jLabelThoigianchieu;
    private javax.swing.JLabel jLabelTimkiem;
    private javax.swing.JPanel jPanelInforKhuyenmai;
    private javax.swing.JScrollPane jScrollPaneBangKhuyenmai;
    private javax.swing.JTable jTableQLKhuyenmai;
    private javax.swing.JTextField jTextFieldMagia;
    private javax.swing.JTextField jTextFieldMalichchieu;
    private javax.swing.JTextField jTextFieldMaphim;
    private javax.swing.JTextField jTextFieldMaphong;
    private javax.swing.JTextField jTextFieldThoigianchieu;
    private javax.swing.JTextField jTextFieldTimkiem;
    // End of variables declaration//GEN-END:variables
}
